const fs = require('fs');
const path = require('path');

const vocab = [
  { "word_index": 1, "word": "able", "pronunciation": "AY-bul", "meaning": "having the power or skill to do something", "example_sentence": "I am able to speak a little English now." },
  { "word_index": 2, "word": "about", "pronunciation": "uh-BOUT", "meaning": "on the subject of; connected with", "example_sentence": "We are talking about our favorite movies." },
  { "word_index": 3, "word": "above", "pronunciation": "uh-BUHV", "meaning": "at or to a higher place than something", "example_sentence": "The birds are flying above the trees." },
  { "word_index": 4, "word": "accept", "pronunciation": "uhk-SEPT", "meaning": "to agree to take something", "example_sentence": "Please accept this small gift from me." },
  { "word_index": 5, "word": "account", "pronunciation": "uh-KOUNT", "meaning": "an arrangement with a bank or company", "example_sentence": "I opened a new bank account today." },
  { "word_index": 6, "word": "achieve", "pronunciation": "uh-CHEEV", "meaning": "to succeed in doing something by effort", "example_sentence": "You can achieve your goal if you study hard." },
  { "word_index": 7, "word": "across", "pronunciation": "uh-KRAWS", "meaning": "from one side to the other", "example_sentence": "We walked across the street to the cafe." },
  { "word_index": 8, "word": "act", "pronunciation": "akt", "meaning": "to do something for a particular reason", "example_sentence": "You must act quickly in an emergency." },
  { "word_index": 9, "word": "active", "pronunciation": "AK-tiv", "meaning": "busy and doing a lot of things", "example_sentence": "She is very active and loves playing sports." },
  { "word_index": 10, "word": "actor", "pronunciation": "AK-ter", "meaning": "a person who performs in a play or movie", "example_sentence": "He is a famous actor in action movies." },
  { "word_index": 11, "word": "actual", "pronunciation": "AK-choo-uhl", "meaning": "real and not general or guessed", "example_sentence": "The actual cost was higher than we expected." },
  { "word_index": 12, "word": "add", "pronunciation": "ad", "meaning": "to put something together with something else", "example_sentence": "Please add some sugar to my coffee." },
  { "word_index": 13, "word": "address", "pronunciation": "uh-DRES", "meaning": "the details of where a building is", "example_sentence": "What is the address of your new house?" },
  { "word_index": 14, "word": "admit", "pronunciation": "uhd-MIT", "meaning": "to agree that something is true", "example_sentence": "He had to admit that he made a mistake." },
  { "word_index": 15, "word": "adult", "pronunciation": "uh-DUHLT", "meaning": "a fully grown person", "example_sentence": "Tickets are cheaper for children than for adults." },
  { "word_index": 16, "word": "advice", "pronunciation": "uhd-VAYS", "meaning": "an opinion about what someone should do", "example_sentence": "She gave me some excellent advice about my career." },
  { "word_index": 17, "word": "afford", "pronunciation": "uh-FAWRD", "meaning": "to have enough money to buy something", "example_sentence": "I cannot afford to buy a new car right now." },
  { "word_index": 18, "word": "afraid", "pronunciation": "uh-FRAYD", "meaning": "feeling fear or worry", "example_sentence": "Do not be afraid of making mistakes when speaking." },
  { "word_index": 19, "word": "after", "pronunciation": "AF-ter", "meaning": "later than something; behind", "example_sentence": "We had dinner after watching the movie." },
  { "word_index": 20, "word": "afternoon", "pronunciation": "af-ter-NOON", "meaning": "the period between midday and evening", "example_sentence": "I usually study English in the afternoon." },
  { "word_index": 21, "word": "again", "pronunciation": "uh-GEN", "meaning": "one more time; once more", "example_sentence": "Can you say that again, please?" },
  { "word_index": 22, "word": "against", "pronunciation": "uh-GENST", "meaning": "opposing or disagreeing with someone/something", "example_sentence": "We are playing against the best team tomorrow." },
  { "word_index": 23, "word": "age", "pronunciation": "ayj", "meaning": "the number of years someone has lived", "example_sentence": "She looks young for her age." },
  { "word_index": 24, "word": "agency", "pronunciation": "AY-juhn-see", "meaning": "a business that provides a service", "example_sentence": "He works at a travel agency in the city." },
  { "word_index": 25, "word": "agent", "pronunciation": "AY-juhnt", "meaning": "a person who acts for another person or group", "example_sentence": "Our real estate agent helped us find a nice apartment." },
  { "word_index": 26, "word": "ago", "pronunciation": "uh-GOH", "meaning": "back in time; in the past", "example_sentence": "I finished my homework an hour ago." },
  { "word_index": 27, "word": "agree", "pronunciation": "uh-GREE", "meaning": "to have the same opinion as someone else", "example_sentence": "I agree with your idea completely." },
  { "word_index": 28, "word": "ahead", "pronunciation": "uh-HED", "meaning": "in front of someone or something", "example_sentence": "Walk straight ahead until you see the station." },
  { "word_index": 29, "word": "air", "pronunciation": "air", "meaning": "the mixture of gases that surrounds the earth", "example_sentence": "The mountain air is very clean and fresh." },
  { "word_index": 30, "word": "all", "pronunciation": "awl", "meaning": "the whole number or amount of something", "example_sentence": "All the students passed the test." },
  { "word_index": 31, "word": "allow", "pronunciation": "uh-LOU", "meaning": "to let someone do something", "example_sentence": "They do not allow smoking inside the library." },
  { "word_index": 32, "word": "almost", "pronunciation": "AWL-mohst", "meaning": "nearly; not quite", "example_sentence": "Dinner is almost ready, please sit down." },
  { "word_index": 33, "word": "alone", "pronunciation": "uh-LOHN", "meaning": "without any other people", "example_sentence": "She likes walking alone in the park." },
  { "word_index": 34, "word": "along", "pronunciation": "uh-LAWNG", "meaning": "from one end to the other of something", "example_sentence": "We walked along the river bank." },
  { "word_index": 35, "word": "already", "pronunciation": "awl-RED-ee", "meaning": "before now or before a particular time", "example_sentence": "I have already finished my homework." },
  { "word_index": 36, "word": "also", "pronunciation": "AWL-soh", "meaning": "in addition; too", "example_sentence": "He speaks Spanish and also a little French." },
  { "word_index": 37, "word": "although", "pronunciation": "awl-THOH", "meaning": "even though; despite the fact that", "example_sentence": "Although it was raining, we went for a walk." },
  { "word_index": 38, "word": "always", "pronunciation": "AWL-wayz", "meaning": "at all times; every time", "example_sentence": "She always drinks tea in the morning." },
  { "word_index": 39, "word": "amount", "pronunciation": "uh-MOUNT", "meaning": "a quantity of something", "example_sentence": "We need a large amount of water for the garden." },
  { "word_index": 40, "word": "ancient", "pronunciation": "AYN-shuhnt", "meaning": "belonging to a period of history long ago", "example_sentence": "They visited the ancient temples in Kyoto." },
  { "word_index": 41, "word": "anger", "pronunciation": "ANG-ger", "meaning": "a strong feeling of being displeased", "example_sentence": "He tried to control his anger when he heard the news." },
  { "word_index": 42, "word": "angle", "pronunciation": "ANG-guhl", "meaning": "the space between two lines that meet", "example_sentence": "The camera was set at a low angle." },
  { "word_index": 43, "word": "animal", "pronunciation": "AN-i-muhl", "meaning": "a living thing that is not a plant", "example_sentence": "A dog is a very loyal animal." },
  { "word_index": 44, "word": "announce", "pronunciation": "uh-NOUNS", "meaning": "to make something known publicly", "example_sentence": "They will announce the winner tomorrow." },
  { "word_index": 45, "word": "another", "pronunciation": "uh-NUHTH-er", "meaning": "one more; different person or thing", "example_sentence": "Can I have another cup of coffee?" },
  { "word_index": 46, "word": "answer", "pronunciation": "AN-ser", "meaning": "something said or written to reply to a question", "example_sentence": "He gave a clear answer to my question." },
  { "word_index": 47, "word": "anxiety", "pronunciation": "ang-ZAY-i-tee", "meaning": "a feeling of worry or nervousness", "example_sentence": "He felt a lot of anxiety before the exam." },
  { "word_index": 48, "word": "any", "pronunciation": "EN-ee", "meaning": "one or some of a thing, no matter which", "example_sentence": "Do you have any questions for me?" },
  { "word_index": 49, "word": "anyone", "pronunciation": "EN-ee-wuhn", "meaning": "any person", "example_sentence": "Anyone can join the English club." },
  { "word_index": 50, "word": "anything", "pronunciation": "EN-ee-thing", "meaning": "any thing, no matter which", "example_sentence": "Is there anything else you need?" },
  { "word_index": 51, "word": "apart", "pronunciation": "uh-PAHRT", "meaning": "separated by a distance or time", "example_sentence": "The two houses are about one mile apart." },
  { "word_index": 52, "word": "apartment", "pronunciation": "uh-PAHRT-muhnt", "meaning": "a set of rooms for living in, usually on one floor", "example_sentence": "They live in a modern apartment in Tokyo." },
  { "word_index": 53, "word": "apologize", "pronunciation": "uh-PAHL-uh-jayz", "meaning": "to say that you are sorry for something", "example_sentence": "You should apologize for being late." },
  { "word_index": 54, "word": "apparent", "pronunciation": "uh-PAR-uhnt", "meaning": "easy to see or understand; clear", "example_sentence": "It was apparent that she was not happy." },
  { "word_index": 55, "word": "appeal", "pronunciation": "uh-PEEL", "meaning": "a deeply felt request for help or money", "example_sentence": "The police made an appeal for information." },
  { "word_index": 56, "word": "appear", "pronunciation": "uh-PEER", "meaning": "to start to be seen or to exist", "example_sentence": "A dark cloud started to appear in the sky." },
  { "word_index": 57, "word": "apple", "pronunciation": "AP-uhl", "meaning": "a round fruit with red or green skin", "example_sentence": "An apple a day keeps the doctor away." },
  { "word_index": 58, "word": "apply", "pronunciation": "uh-PLAY", "meaning": "to make a formal request for something", "example_sentence": "I want to apply for a visa to travel." },
  { "word_index": 59, "word": "appoint", "pronunciation": "uh-POYNT", "meaning": "to choose someone for a job or position", "example_sentence": "They will appoint a new manager soon." },
  { "word_index": 60, "word": "area", "pronunciation": "AIR-ee-uh", "meaning": "a part of a place, town, or country", "example_sentence": "There is a nice play area for kids here." },
  { "word_index": 61, "word": "argue", "pronunciation": "AHR-gyoo", "meaning": "to speak angrily to someone because you disagree", "example_sentence": "They always argue about what to watch." },
  { "word_index": 62, "word": "arm", "pronunciation": "ahrm", "meaning": "either of the two long parts of the body", "example_sentence": "He broke his arm while skiing." },
  { "word_index": 63, "word": "army", "pronunciation": "AHR-mee", "meaning": "a large group of soldiers trained to fight", "example_sentence": "He joined the army after high school." },
  { "word_index": 64, "word": "around", "pronunciation": "uh-ROUND", "meaning": "in a circle or in all directions", "example_sentence": "We walked around the town center." },
  { "word_index": 65, "word": "arrange", "pronunciation": "uh-RAYNJ", "meaning": "to plan or organize something", "example_sentence": "I will arrange a meeting for next week." },
  { "word_index": 66, "word": "arrest", "pronunciation": "uh-REST", "meaning": "when the police take someone to keep them", "example_sentence": "The police had to arrest the thief." },
  { "word_index": 67, "word": "arrive", "pronunciation": "uh-RAYV", "meaning": "to reach a place at the end of a journey", "example_sentence": "What time does the train arrive?" },
  { "word_index": 68, "word": "art", "pronunciation": "ahrt", "meaning": "paintings, drawings, and sculptures", "example_sentence": "She is studying modern art at university." },
  { "word_index": 69, "word": "article", "pronunciation": "AHR-ti-kuhl", "meaning": "a piece of writing in a newspaper or magazine", "example_sentence": "I read an interesting article about AI." },
  { "word_index": 70, "word": "artist", "pronunciation": "AHR-tist", "meaning": "a person who creates art, especially paintings", "example_sentence": "He is a talented artist who paints landscapes." },
  { "word_index": 71, "word": "as", "pronunciation": "az", "meaning": "used to describe a role or state of someone/something", "example_sentence": "She works as a teacher in a school." },
  { "word_index": 72, "word": "ask", "pronunciation": "ask", "meaning": "to say something to get information", "example_sentence": "Can I ask you a personal question?" },
  { "word_index": 73, "word": "asleep", "pronunciation": "uh-SLEEP", "meaning": "in a state of sleep; sleeping", "example_sentence": "The baby is fast asleep in the crib." },
  { "word_index": 74, "word": "assist", "pronunciation": "uh-SIST", "meaning": "to help someone to do something", "example_sentence": "The guide will assist you during the tour." },
  { "word_index": 75, "word": "assistant", "pronunciation": "uh-SIS-tuhnt", "meaning": "a person who helps someone in a job", "example_sentence": "He works as a research assistant." },
  { "word_index": 76, "word": "associate", "pronunciation": "uh-SOH-shee-ayt", "meaning": "to connect someone or something in your mind", "example_sentence": "Most people associate summer with hot weather." },
  { "word_index": 77, "word": "assume", "pronunciation": "uh-SOOM", "meaning": "to think that something is true without proof", "example_sentence": "Do not assume that everything online is true." },
  { "word_index": 78, "word": "at", "pronunciation": "at", "meaning": "used to show a place, direction, or time", "example_sentence": "Let us meet at the station at 5 PM." },
  { "word_index": 79, "word": "attack", "pronunciation": "uh-TAK", "meaning": "an act of using violence to hurt someone", "example_sentence": "The army launched an attack at dawn." },
  { "word_index": 80, "word": "attempt", "pronunciation": "uh-TEMPT", "meaning": "an act of trying to do something difficult", "example_sentence": "This is his first attempt to run a marathon." },
  { "word_index": 81, "word": "attend", "pronunciation": "uh-TEND", "meaning": "to go to or be present at a meeting, class, etc.", "example_sentence": "He wants to attend the conference next month." },
  { "word_index": 82, "word": "attention", "pronunciation": "uh-TEN-shuhn", "meaning": "the act of listening to or looking at someone/something", "example_sentence": "Please pay attention to the instructions." },
  { "word_index": 83, "word": "attitude", "pronunciation": "AT-i-tood", "meaning": "the way you think or feel about someone/something", "example_sentence": "She has a very positive attitude toward life." },
  { "word_index": 84, "word": "attract", "pronunciation": "uh-TRAKT", "meaning": "to pull or draw someone/something toward you", "example_sentence": "Flowers attract bees and butterflies." },
  { "word_index": 85, "word": "audience", "pronunciation": "AW-dee-uhns", "meaning": "the group of people watching a show or play", "example_sentence": "The audience cheered at the end of the show." },
  { "word_index": 86, "word": "author", "pronunciation": "AW-ther", "meaning": "a person who writes a book or article", "example_sentence": "Who is the author of this novel?" },
  { "word_index": 87, "word": "authority", "pronunciation": "uh-THAWR-i-tee", "meaning": "the power or right to give orders", "example_sentence": "She has the authority to make decisions." },
  { "word_index": 88, "word": "available", "pronunciation": "uh-VAY-luh-buhl", "meaning": "ready or free to be used or bought", "example_sentence": "Is this seat available, or is someone sitting here?" },
  { "word_index": 89, "word": "average", "pronunciation": "AV-er-ij", "meaning": "typical or normal; middle level", "example_sentence": "The average temperature in June is 25 degrees." },
  { "word_index": 90, "word": "avoid", "pronunciation": "uh-VOYD", "meaning": "to stay away from someone or something", "example_sentence": "You should avoid eating too much junk food." },
  { "word_index": 91, "word": "award", "pronunciation": "uh-WAWRD", "meaning": "a prize given to someone for an achievement", "example_sentence": "He won the Best Actor award this year." },
  { "word_index": 92, "word": "aware", "pronunciation": "uh-WAIR", "meaning": "knowing or realizing something", "example_sentence": "Are you aware of the new rules?" },
  { "word_index": 93, "word": "away", "pronunciation": "uh-WAY", "meaning": "to or at a distance from a place or person", "example_sentence": "Please put your books away." },
  { "word_index": 94, "word": "baby", "pronunciation": "BAY-bee", "meaning": "a very young child or animal", "example_sentence": "The baby fell asleep in her arms." },
  { "word_index": 95, "word": "back", "pronunciation": "bak", "meaning": "the part of the body opposite to the chest", "example_sentence": "He has a sore back from sitting too long." },
  { "word_index": 96, "word": "bad", "pronunciation": "bad", "meaning": "not good; of poor quality", "example_sentence": "I have a bad cold and cannot go to work." },
  { "word_index": 97, "word": "bag", "pronunciation": "bag", "meaning": "a container made of thin cloth, paper, or plastic", "example_sentence": "She put her wallet inside her bag." },
  { "word_index": 98, "word": "balance", "pronunciation": "BAL-uhns", "meaning": "a state where things are equal or steady", "example_sentence": "It is important to keep a good work-life balance." },
  { "word_index": 99, "word": "ball", "pronunciation": "bawl", "meaning": "a round object used in games and sports", "example_sentence": "He kicked the ball into the goal." },
  { "word_index": 100, "word": "band", "pronunciation": "band", "meaning": "a group of musicians who play music together", "example_sentence": "My favorite rock band is playing tonight." }
];

// Generate words from 101 to 300 programmatically with simple standard dictionary values
const baseWordsList = [
  ["bank", "bangk", "an organization where people keep money", "I need to go to the bank to withdraw some cash."],
  ["bar", "bahr", "a place where drinks are sold and drunk", "We met at a quiet bar near the hotel."],
  ["base", "bays", "the lowest part or bottom of something", "The base of the statue is made of stone."],
  ["basic", "BAY-sik", "forming the most important part of something", "He has a basic knowledge of computer programming."],
  ["basis", "BAY-sis", "the reason or foundation for something", "This story is the basis for the movie."],
  ["battle", "BAT-uhl", "a fight between armies in a war", "The battle lasted for three days."],
  ["be", "bee", "to exist or have a state/identity", "I want to be a doctor when I grow up."],
  ["beach", "beech", "an area of sand next to the sea", "We spent the weekend lying on the beach."],
  ["bear", "bair", "a large heavy animal with thick fur", "We saw a brown bear in the forest."],
  ["beat", "beet", "to defeat someone in a game or fight", "Our team managed to beat the champions."],
  ["beautiful", "BYOO-ti-fuhl", "very attractive to look at; lovely", "The sunset over the ocean was beautiful."],
  ["beauty", "BYOO-tee", "the quality of being pleasing to look at", "She appreciated the beauty of the old garden."],
  ["because", "bi-KAWZ", "for the reason that; since", "I stayed at home because it was raining."],
  ["become", "bi-KUHM", "to start to be something", "He wants to become a professional writer."],
  ["bed", "bed", "a piece of furniture that you sleep on", "I was so tired that I went straight to bed."],
  ["bedroom", "BED-room", "a room for sleeping in", "Her bedroom has a large window facing the garden."],
  ["beer", "beer", "an alcoholic drink made from grain", "He ordered a cold beer at the restaurant."],
  ["before", "bi-FAWR", "earlier than a particular time", "Please wash your hands before eating."],
  ["begin", "bi-GIN", "to start to do or happen", "The class will begin at nine o'clock."],
  ["beginning", "bi-GIN-ing", "the start of something", "I liked the beginning of the movie best."],
  ["behavior", "bi-HAY-vyer", "the way that someone acts or behaves", "His polite behavior impressed everyone."],
  ["behind", "bi-HAYND", "at the back of someone or something", "The keys fell behind the sofa."],
  ["believe", "bi-LEEV", "to think that something is true", "I believe that he is telling the truth."],
  ["bell", "bel", "a hollow metal object that makes a ringing sound", "The church bell rings every hour."],
  ["below", "bi-LOH", "in a lower position than something", "Please read the instructions below."],
  ["belt", "belt", "a strip of leather worn around the waist", "He fastened his seat belt before driving."],
  ["bend", "bend", "to curve or make something curve", "You have to bend your knees to jump."],
  ["beneath", "bi-NEETH", "under or in a lower position than", "The valley lay beneath the clouds."],
  ["benefit", "BEN-uh-fit", "an advantage or useful effect", "Exercise offers a benefit to your health."],
  ["beside", "bi-SAYD", "next to or at the side of", "He came and sat beside me."],
  ["best", "best", "of the most excellent quality", "This is the best pizza I have ever eaten."],
  ["bet", "bet", "to risk money on a future event", "I bet he will win the race today."],
  ["better", "BET-er", "of a higher standard or quality", "I feel much better after a good sleep."],
  ["between", "bi-TWEEN", "in the space separating two things", "The shop is located between the bank and the bakery."],
  ["beyond", "bee-AHND", "on the further side of; past", "The road continues beyond the hills."],
  ["bicycle", "BAY-si-kuhl", "a vehicle with two wheels that you pedal", "He rides his bicycle to work every day."],
  ["big", "big", "large in size, degree, or amount", "They live in a big house in the suburbs."],
  ["bill", "bil", "a document showing how much money you owe", "The waiter brought us the bill for dinner."],
  ["billion", "BIL-yuhn", "the number 1,000,000,000", "The world population is over eight billion."],
  ["bird", "burd", "a creature with feathers and wings", "A blue bird is sitting on the fence."],
  ["birth", "burth", "the time when a baby is born", "She gave birth to a healthy baby girl."],
  ["bit", "bit", "a small piece or amount of something", "Can I have a little bit of cake?"],
  ["bite", "bayt", "to use your teeth to cut something", "Be careful, the dog might bite you."],
  ["black", "blak", "having the darkest color like coal", "She wore a elegant black dress to the party."],
  ["blade", "blayd", "the flat sharp part of a knife or tool", "The blade of this knife is very sharp."],
  ["blame", "blaym", "to think or say that someone is responsible for a bad thing", "Do not blame others for your mistakes."],
  ["blank", "blangk", "empty, with no writing or decoration", "Please write your name on a blank sheet of paper."],
  ["blind", "blaynd", "unable to see", "He has a guide dog because he is blind."],
  ["block", "blahk", "a solid piece of hard material", "The children are playing with wooden blocks."],
  ["blood", "bluhd", "the red liquid that flows through the body", "He donated blood at the hospital today."],
  ["blow", "bloh", "when air moves; to force air out", "The wind began to blow very hard."],
  ["blue", "bloo", "having the color of the clear sky", "She has beautiful blue eyes."],
  ["board", "bawrd", "a flat piece of wood or other hard material", "The teacher wrote the words on the board."],
  ["boat", "boht", "a vehicle used for traveling on water", "We took a small boat across the lake."],
  ["body", "BAHD-ee", "the whole physical structure of a person", "Regular exercise is good for your body."],
  ["bomb", "bahm", "a weapon designed to explode and cause damage", "The bomb exploded near the bridge."],
  ["bond", "bahnd", "something that joins or connects people", "There is a strong bond between the two sisters."],
  ["bone", "bohn", "any of the hard parts inside the body", "He broke a bone in his foot."],
  ["book", "buk", "a written work that is printed or online", "I am reading a very interesting book now."],
  ["boot", "boot", "a sturdy shoe that covers the foot and ankle", "She bought a pair of warm leather boots."],
  ["border", "BAWR-der", "the line dividing two countries", "We had to show our passports at the border."],
  ["bore", "bawr", "to make someone feel tired or uninterested", "His long speeches always bore the audience."],
  ["born", "bawrn", "brought into life by birth", "She was born in Tokyo in 2003."],
  ["borrow", "BAHR-oh", "to take something with permission to return it", "Can I borrow your pen for a second?"],
  ["boss", "bahs", "the person who is in charge of you at work", "My boss gave me some useful advice today."],
  ["both", "bohth", "two people or things together", "Both of my brothers live in Osaka."],
  ["bottle", "BAHT-uhl", "a container for liquids, usually glass or plastic", "He drank a bottle of water after running."],
  ["bottom", "BAHT-uhm", "the lowest part of something", "The answers are at the bottom of the page."],
  ["bound", "bound", "certain or extremely likely to happen", "You are bound to pass the test if you study."],
  ["bowl", "bohl", "a round deep dish used for food", "She ate a bowl of hot soup for lunch."],
  ["box", "bahks", "a container with flat sides and a lid", "Put all the toys back in the box."],
  ["boy", "boy", "a male child or young man", "The young boy was flying a kite in the park."],
  ["brain", "brayn", "the organ inside the head that controls thought", "The brain needs sleep to function well."],
  ["branch", "branch", "a part of a tree that grows out from the trunk", "A bird is sitting on a branch of the tree."],
  ["brand", "brand", "a product made by a particular company", "What brand of shoes do you prefer?"],
  ["bread", "bred", "a common food made from flour and water", "I usually eat bread and butter for breakfast."],
  ["break", "brayk", "to separate into pieces by force; a short rest", "Be careful not to break the glass. Let us take a short break."],
  ["breakfast", "BREK-fuhst", "the first meal of the day", "I always eat breakfast at seven o'clock."],
  ["breast", "brest", "either of the two soft organs on a woman's chest", "The mother held the baby to her breast."],
  ["breath", "breth", "the air that you take in and blow out", "He took a deep breath before speaking."],
  ["breathe", "breeth", "to take air into your lungs and send it out", "It is hard to breathe in this hot room."],
  ["bridge", "brij", "a structure built over a river or road", "We walked across the old stone bridge."],
  ["brief", "breef", "lasting only a short time; short", "The manager gave a brief summary of the project."],
  ["bright", "brayt", "shining with a lot of light", "The stars are very bright tonight."],
  ["bring", "bring", "to come to a place with someone/something", "Please bring your dictionary to class tomorrow."],
  ["broad", "brawd", "wide; including a large variety of things", "He has a broad knowledge of world history."],
  ["brother", "BRUH-ther", "a boy or man who has the same parents as you", "My older brother is a university student."],
  ["brown", "broun", "having the color of earth or wood", "He has brown hair and brown eyes."],
  ["brush", "bruhn", "an object with bristles used for cleaning or painting", "You should brush your teeth twice a day."],
  ["budget", "BUHJ-it", "the amount of money available for a purpose", "We are working on a very tight budget."],
  ["build", "bild", "to make something by putting parts together", "They plan to build a new library here."],
  ["building", "BIL-ding", "a structure with walls and a roof", "That tall building is a famous hotel."],
  ["bullet", "BUHL-it", "a small metal object fired from a gun", "The bullet hit the target precisely."],
  ["bunch", "buhnch", "a group of things growing or tied together", "He bought a bunch of flowers for his mother."],
  ["burn", "burn", "to damage or destroy something by fire", "The campfire began to burn brightly."],
  ["burst", "burst", "to break open suddenly", "The balloon will burst if you blow it up more."],
  ["bury", "BER-ee", "to put a dead body or object in the ground", "They decided to bury the treasure under the tree."],
  ["bus", "buhs", "a large vehicle that carries passengers along a route", "I catch the bus to school every morning."],
  ["business", "BIZ-nis", "the activity of making, buying, or selling things", "He started a new import-export business."],
  ["busy", "BIZ-ee", "having a lot of things to do; not free", "She is busy preparing for her exams."],
  ["but", "buht", "used to introduce a contrasting statement", "I want to go, but I have no money."],
  ["butter", "BUHT-er", "a yellow fat made from milk", "Please spread some butter on the toast."],
  ["button", "BUHT-uhn", "a small round object used to fasten clothes", "He lost a button from his shirt."],
  ["buy", "bay", "to get something by paying money", "I want to buy some fresh fruit."],
  ["by", "bay", "near; not later than; through the action of", "The school is by the river. Please finish it by Monday."],
  ["cabin", "KAB-in", "a small simple house, usually made of wood", "We stayed in a cozy cabin in the woods."],
  ["cabinet", "KAB-i-nit", "a piece of furniture with shelves or drawers", "Keep the cups in the kitchen cabinet."],
  ["cable", "KAY-buhl", "a strong thick wire or rope", "The television is connected to the cable."],
  ["cake", "kayk", "a sweet baked food made from flour and sugar", "She baked a chocolate cake for my birthday."],
  ["calculate", "KAL-kyuh-layt", "to find a number using math", "We need to calculate the cost of our trip."],
  ["call", "kawl", "to give a name; to telephone someone", "Please call me when you arrive."],
  ["calm", "kahm", "peaceful, quiet, and not worried", "The sea was very calm this morning."],
  ["camera", "KAM-er-uh", "a device used for taking photos or videos", "He bought a new digital camera."],
  ["camp", "kamp", "a place where people stay in tents", "We set up our camp near the river."],
  ["campaign", "kam-PAYN", "a planned series of activities to achieve a goal", "The politician started his election campaign."],
  ["can", "kan", "to be able to do something", "She can speak English very fluently."],
  ["cancel", "KAN-suhl", "to decide that a planned event will not happen", "They had to cancel the meeting due to rain."],
  ["cancer", "KAN-ser", "a serious disease caused by abnormal cells", "He is recovering from cancer treatment."],
  ["candidate", "KAN-di-dayt", "a person who is trying to be elected", "She is a candidate for the mayor position."],
  ["candle", "KAN-duhl", "a stick of wax that burns to give light", "We lit a candle when the power went out."],
  ["candy", "KAN-dee", "sweet food made with sugar", "Kids love eating colorful candy."],
  ["cap", "kap", "a type of soft hat with a curved front part", "He wore a baseball cap to block the sun."],
  ["capable", "KAY-puh-buhl", "having the ability to do something well", "She is a very capable manager."],
  ["capacity", "kuh-PAS-i-tee", "the maximum amount that something can contain", "The stadium has a capacity of fifty thousand."],
  ["capital", "KAP-i-tuhl", "the city where the government is located", "Paris is the capital of France."],
  ["captain", "KAP-tin", "the person in command of a ship or team", "He is the captain of our football team."],
  ["capture", "KAP-cher", "to catch a person or animal by force", "The soldiers managed to capture the castle."],
  ["car", "kahr", "a road vehicle with four wheels and an engine", "She drives a small red car to work."],
  ["card", "kahrd", "a small piece of stiff paper or plastic", "He paid for the groceries with a credit card."],
  ["care", "kair", "to feel interest or worry about someone/something", "I really care about my family's health."],
  ["career", "kuh-REER", "a job or profession that you do for a long time", "She wants a career in medical research."],
  ["careful", "KAIR-fuhl", "giving attention to avoid danger or mistakes", "Please be careful when you cross the street."],
  ["careless", "KAIR-lis", "not giving enough attention to avoid mistakes", "It was careless of him to lose his keys."],
  ["cargo", "KAHR-goh", "goods carried on a ship, plane, or truck", "The cargo ship arrived at the port today."],
  ["carpet", "KAHR-pit", "a thick heavy cover for a floor", "We bought a soft blue carpet for the living room."],
  ["carriage", "KAR-ij", "a vehicle with wheels pulled by horses", "They rode in a horse-drawn carriage."],
  ["carry", "KAR-ee", "to hold and move something to another place", "Could you help me carry these heavy bags?"],
  ["case", "kays", "a particular situation or example of something", "In this case, the rules do not apply."],
  ["cash", "kash", "money in the form of coins or notes", "Do you want to pay in cash or by card?"],
  ["cast", "kast", "to throw something; all the actors in a play", "He cast his fishing line into the water."],
  ["castle", "KAS-uhl", "a large strong building built in the past", "We visited a beautiful historic castle in Europe."],
  ["cat", "kat", "a small furry animal kept as a pet", "A cat is sleeping on the windowsill."],
  ["catch", "kach", "to stop and hold a moving object", "Try to catch the ball before it drops."],
  ["category", "KAT-uh-gawr-ee", "a group of people or things with shared qualities", "Which category does this book belong to?"],
  ["cause", "kawz", "to make something happen; the reason for something", "A small spark can cause a large forest fire."],
  ["cave", "kayv", "a large natural hole in the side of a hill", "We explored a dark cave on our vacation."],
  ["ceiling", "SEE-ling", "the inner surface of the top of a room", "They painted the bedroom ceiling white."],
  ["celebrate", "SEL-uh-brayt", "to do something special for an event", "We went out to celebrate her graduation."],
  ["celebrity", "suh-LEB-ri-tee", "a famous person", "She became a global celebrity after the movie."],
  ["cell", "sel", "the smallest basic unit of a living thing", "Red blood cells carry oxygen around the body."],
  ["cemetery", "SEM-uh-ter-ee", "an area of ground where dead people are buried", "We placed flowers on the grave in the cemetery."],
  ["center", "SEN-ter", "the middle point or part of something", "The fountain is in the center of the square."],
  ["central", "SEN-truhl", "located in the middle of something", "The central station is very busy at rush hour."],
  ["century", "SEN-chuh-ee", "a period of one hundred years", "We live in the twenty-first century."],
  ["ceremony", "SER-uh-moh-nee", "a formal public or religious event", "The wedding ceremony was beautiful."],
  ["certain", "SUR-tuhn", "sure and having no doubt about something", "I am certain that I locked the door."],
  ["certainly", "SUR-tuhn-lee", "without any doubt; definitely", "I will certainly help you with your project."],
  ["chain", "chayn", "a row of metal rings connected together", "He locked his bicycle with a strong chain."],
  ["chair", "chair", "a piece of furniture for one person to sit on", "Please take a chair and sit down."],
  ["chairman", "CHAIR-muhn", "the person in charge of a meeting or company", "The chairman opened the meeting with a speech."],
  ["challenge", "CHAL-inj", "something new and difficult that needs effort", "Learning a new language is a great challenge."],
  ["chamber", "CHAYM-ber", "a hall or large room for formal meetings", "The council met in the town chamber."],
  ["champion", "CHAMP-ee-uhn", "a person or team that wins a competition", "She is the world chess champion."],
  ["chance", "chans", "the possibility of something happening", "Is there any chance of rain today?"],
  ["change", "chaynjs", "to make or become different; to swap", "I need to change my wet clothes."],
  ["channel", "CHAN-uhl", "a television station; a route for water", "Switch to the sports channel, please."],
  ["chaos", "KAY-ahs", "a state of total confusion and lack of order", "The heavy snow caused chaos on the roads."],
  ["chapter", "CHAP-ter", "a section of a book with a number or title", "I am reading the third chapter of the book."],
  ["character", "KAR-ik-ter", "the qualities of a person; a person in a book", "She has a very strong and kind character."],
  ["charge", "chahrj", "the price asked for goods or services", "There is no extra charge for delivery."],
  ["charity", "CHAR-i-tee", "an organization that helps people in need", "All the money raised will go to a local charity."],
  ["chart", "chahrt", "a drawing that shows information simply", "The pie chart shows our monthly expenses."],
  ["chase", "chays", "to run after someone/something to catch them", "The dog loves to chase birds in the park."],
  ["chat", "chat", "to talk in a friendly, informal way", "We sat in the cafe and had a nice chat."],
  ["cheap", "cheep", "costing little money; not expensive", "Tickets are cheaper if you buy them online."],
  ["cheat", "cheet", "to act dishonestly to gain an advantage", "You should never cheat on an exam."],
  ["check", "chek", "to examine something to make sure it is correct", "Please check your answers before submitting."],
  ["cheek", "cheek", "either side of the face below the eyes", "She kissed him on the cheek."],
  ["cheer", "cheer", "to shout loudly to show approval or support", "The crowd began to cheer for the team."],
  ["cheerful", "CHEER-fuhl", "happy and showing it by behavior", "She always has a cheerful smile on her face."],
  ["cheese", "cheez", "a yellow or white food made from milk", "I love eating bread with melted cheese."],
  ["chef", "shef", "a professional cook in a restaurant", "The head chef prepared a special dinner for us."],
  ["chemical", "KEM-i-kuhl", "a substance produced by chemistry", "They do not use harmful chemicals on these crops."],
  ["chemistry", "KEM-i-stree", "the scientific study of substances", "We did an interesting experiment in chemistry class."],
  ["chest", "chest", "the upper front part of the body", "He felt a sudden pain in his chest."],
  ["chicken", "CHIK-in", "a common bird kept for its eggs and meat", "We had grilled chicken and salad for dinner."],
  ["chief", "cheef", "most important; leader of a group", "The chief reason for our success was teamwork."],
  ["child", "chayld", "a young human who is not yet an adult", "The child was playing happily with her toys."],
  ["childhood", "CHAYLD-hud", "the period of time when you are a child", "She had a very happy childhood in the countryside."],
  ["chin", "chin", "the part of the face below the mouth", "He rested his chin on his hand."],
  ["chocolate", "CHAHK-lit", "a sweet brown food made from cocoa", "I bought a bar of dark chocolate."],
  ["choice", "choys", "the act of choosing between things", "You have a choice between tea and coffee."],
  ["choose", "chooz", "to pick someone or something from a group", "It is difficult to choose what to wear today."],
  ["church", "church", "a building where Christians go to worship", "The church was built in the twelfth century."],
  ["cigarette", "SIG-uh-ret", "a thin tube of paper filled with tobacco", "He lit a cigarette while waiting for the bus."],
  ["cinema", "SIN-uh-muh", "a theater where movies are shown", "We are going to the cinema this evening."],
  ["circle", "SUR-kuhl", "a completely round flat shape", "The children sat in a circle on the floor."],
  ["circumstance", "SUR-kuhm-stans", "the facts or conditions of a situation", "The police are investigating the circumstance of the accident."],
  ["citizen", "SIT-i-zuhn", "a person who is a legal member of a country", "He is a citizen of both Japan and Canada."],
  ["city", "SIT-ee", "a large and important town", "Tokyo is a very clean and safe city."]
];

// Append remaining words programmatically to ensure exactly 300 words are generated
const remainingWords = baseWordsList.map((item, index) => {
  return {
    "word_index": 101 + index,
    "word": item[0],
    "pronunciation": item[1],
    "meaning": item[2],
    "example_sentence": item[3]
  };
});

const fullVocab = [...vocab, ...remainingWords];

// Ensure we have exactly 300 words. Fill with dummy/simple words if short, or trim if long.
while (fullVocab.length < 300) {
  const currentIdx = fullVocab.length + 1;
  fullVocab.push({
    "word_index": currentIdx,
    "word": `word_${currentIdx}`,
    "pronunciation": "PRON-un-see-ay-shuhn",
    "meaning": "a common English vocabulary word used in daily life",
    "example_sentence": `This is an example sentence for vocabulary word number ${currentIdx}.`
  });
}

if (fullVocab.length > 300) {
  fullVocab.length = 300;
}

// Write to vocab.json
const dataDir = path.join(__dirname, '..', 'data');
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir);
}

fs.writeFileSync(path.join(dataDir, 'vocab.json'), JSON.stringify(fullVocab, null, 2), 'utf8');
console.log(`Successfully generated vocab.json with ${fullVocab.length} words!`);
