const fs = require('fs');
const path = require('path');

// 500 words across 9 categories
const library = [];

// Helper to push words
function addWord(word, pronunciation, part, meaning, meaningJa, example, level, category) {
  library.push({
    word,
    pronunciation,
    part_of_speech: part,
    meaning,
    meaning_ja: meaningJa,
    example_sentence: example,
    difficulty_level: level,
    category
  });
}

// 1. emotions (80 words)
const emotions = [
  ["melancholy", "MEL-an-kol-ee", "noun/adjective", "A feeling of deep sadness or thoughtfulness", "憂鬱、もの悲しさ", "The ending of that anime left me with a beautiful melancholy.", "B2"],
  ["bittersweet", "BIT-er-sweet", "adjective", "Both happy and sad at the same time", "甘くて苦い、複雑な気持ち", "Finishing a good anime feels bittersweet.", "B1"],
  ["wholesome", "HOLE-sum", "adjective", "Pure, positive, and making you feel warm inside", "ほっこりする、心温まる", "That anime is so wholesome — it makes me smile every episode.", "B1"],
  ["nostalgic", "nuh-STAL-jik", "adjective", "A sentimental longing for the past", "懐かしい、郷愁にふける", "Listening to that theme song makes me feel nostalgic.", "B1"],
  ["anxious", "ANGK-shuhs", "adjective", "Feeling worried, uneasy, or nervous", "不安な、心配な", "I feel anxious before speaking in English, but practice helps.", "A2"],
  ["overwhelmed", "oh-ver-WHELMD", "adjective", "Having too much to deal with", "圧倒された、いっぱいいっぱいの", "I was overwhelmed by the grammar at first, but now it makes sense.", "B1"],
  ["content", "kuhn-TENT", "adjective", "Happy and satisfied with what you have", "満足している", "She felt content after a long day of studying.", "A2"],
  ["ecstatic", "ek-STAT-ik", "adjective", "Extremely happy or excited", "有頂天の、狂喜乱舞した", "He was ecstatic when he got his placement test score.", "B2"],
  ["devastated", "DEV-uh-stay-tid", "adjective", "Extremely shocked and upset", "打ちのめされた、絶望した", "I was devastated when my streak froze, but luckily I had a shield.", "B2"],
  ["conflicted", "kuhn-FLIK-tid", "adjective", "Having confused or opposing feelings", "葛藤している", "I feel conflicted about who is the best character in the show.", "B1"],
  ["relieved", "ri-LEEVD", "adjective", "Feeling happy because something unpleasant has stopped", "安心した", "I was relieved to pass the vocabulary check.", "A2"],
  ["curious", "KYOOR-ee-uhs", "adjective", "Eager to know or learn something", "好奇心旺盛な", "I am curious about the culture in foreign countries.", "A2"],
  ["enthusiastic", "en-thoo-zee-AS-tik", "adjective", "Showing intense enjoyment or interest", "熱狂的な、やる気のある", "The teacher is very enthusiastic about our diaries.", "B1"],
  ["furious", "FYOOR-ee-uhs", "adjective", "Extremely angry", "激怒した", "He was furious when he lost his notebook.", "B1"],
  ["cheerful", "CHEER-fuhl", "adjective", "Noticeably happy and optimistic", "朗らかな、陽気な", "Her cheerful voice always brightens the classroom.", "A2"],
  ["serene", "suh-REEN", "adjective", "Calm, peaceful, and untroubled", "穏やかな、澄み渡った", "The silent park in the morning felt very serene.", "B2"],
  ["pessimistic", "pes-uh-MIS-tik", "adjective", "Tending to see the worst aspect of things", "悲観的な", "Don't be so pessimistic about your speaking abilities.", "B2"],
  ["optimistic", "op-tuh-MIS-tik", "adjective", "Hopeful and confident about the future", "楽観的な", "I am optimistic about my English journey.", "B1"],
  ["lonely", "LOHN-lee", "adjective", "Sad because one has no friends or company", "寂しい、孤独な", "Living alone in a foreign city can be lonely.", "A1"],
  ["proud", "PROWD", "adjective", "Feeling deep pleasure or satisfaction as a result of achievements", "誇りに思う", "I am proud of my 90-day streak.", "A1"],
  ["embarrassed", "em-BAR-uhst", "adjective", "Feeling self-conscious, confused, or ashamed", "恥ずかしい", "I was embarrassed when I mispronounced the word.", "B1"],
  ["jealous", "JEL-uhs", "adjective", "Feeling resentment against someone's achievements or possessions", "嫉妬深い", "She felt jealous of his natural English pronunciation.", "B1"],
  ["envious", "EN-vee-uhs", "adjective", "Feeling or showing envy", "うらやましい", "I am envious of your translation skills.", "B2"],
  ["grateful", "GRAYT-fuhl", "adjective", "Feeling or showing appreciation for kindness", "感謝している", "I am grateful for the feedback from the teacher.", "A2"],
  ["sympathetic", "sim-puh-THET-ik", "adjective", "Feeling or showing concern for someone", "同情的な", "She was sympathetic to my struggles with listening.", "B2"],
  ["empathetic", "em-puh-THET-ik", "adjective", "Showing an ability to understand and share the feelings of others", "共感できる", "An empathetic teacher makes learning less stressful.", "B2"],
  ["indifferent", "in-DIF-er-uhnt", "adjective", "Having no particular interest or sympathy; unconcerned", "無関心な", "He was indifferent to whether we studied vocab or grammar.", "B2"],
  ["frustrated", "FRUHS-trey-tid", "adjective", "Feeling annoyed or distressed as a result of being unable to achieve something", "イライラした、もどかしい", "Don't get frustrated if you make spelling mistakes.", "B1"],
  ["disappointed", "dis-uh-POIN-tid", "adjective", "Sad or displeased because someone or something has failed to fulfill one's hopes", "失望した", "I was disappointed with my score on the listening quiz.", "B1"],
  ["hopeful", "HOHP-fuhl", "adjective", "Feeling or inspiring optimism about a future event", "希望に満ちた", "We are hopeful that she will pass the placement test.", "A2"],
  ["suspicious", "suh-SPISH-uhs", "adjective", "Having or showing a cautious distrust of someone or something", "疑わしい", "The silent student looked suspicious.", "B1"],
  ["insecure", "in-si-KYOOR", "adjective", "Not confident or assured; uncertain and anxious", "自分に自信のない", "Studying grammar makes me feel insecure sometimes.", "B2"],
  ["confident", "KON-fi-duhnt", "adjective", "Feeling or showing confidence in oneself", "自信のある", "I feel more confident speaking English today.", "B1"],
  ["bewildered", "bih-WIL-dwerd", "adjective", "Perplexed and confused; very puzzled", "途方にくれた、困惑した", "The idiom bewildered me at first.", "B2"],
  ["terrified", "TER-uh-fahyd", "adjective", "Cause to feel extreme fear", "ひどく恐れた", "I was terrified of speaking on microphone.", "B1"],
  ["thrilled", "THRILD", "adjective", "Cause to feel a sudden sensation of excitement and pleasure", "ワクワクした", "I was thrilled to get a freeze shield.", "B1"],
  ["disgusted", "dis-GUHS-tid", "adjective", "Feeling or showing strong disapproval or aversion", "うんざりした", "I was disgusted by the bad behavior.", "B1"],
  ["aggressive", "uh-GRES-iv", "adjective", "Ready or likely to attack or confront", "攻撃的な", "His tone in the debate was a bit aggressive.", "B2"],
  ["defensive", "dih-FEN-siv", "adjective", "Used or intended to defend or protect", "防衛的な", "She got defensive when I corrected her grammar.", "B2"],
  ["submissive", "suhb-MIS-iv", "adjective", "Ready to conform to the authority or will of others", "従順な", "He took a submissive role in the conversation.", "C1"],
  ["ambitious", "am-BISH-uhs", "adjective", "Having or showing a strong desire and determination to succeed", "野心的な", "Yuki is ambitious about mastering 500 words.", "B1"],
  ["greedy", "GREE-dee", "adjective", "Having or showing an intense and selfish desire for something", "強欲な", "Don't be greedy with study points.", "B1"],
  ["arrogant", "AR-uh-guhnt", "adjective", "Having or showing an exaggerated opinion of one's own importance or abilities", "傲慢な", "He spoke in an arrogant manner.", "B2"],
  ["humble", "HUHM-buhl", "adjective", "Having or showing a modest or low estimate of one's own importance", "謙虚な", "Despite being fluent, he remained humble.", "B1"],
  ["passionate", "PASH-uh-nit", "adjective", "Showing or caused by strong feelings or a strong belief", "情熱的な", "She is passionate about foreign music.", "B1"],
  ["desperate", "DES-per-it", "adjective", "Feeling, showing, or involving a hopeless sense that a situation is so bad as to be impossible to deal with", "絶望的な", "He made a desperate attempt to save his streak.", "B1"],
  ["dynamic", "dahy-NAM-ik", "adjective", "Constant change, activity, or progress", "活動的な、動的な", "The language landscape is dynamic.", "B2"],
  ["static", "STAT-ik", "adjective", "Lacking in movement, action, or change", "静的な、変化のない", "His speaking speed was static.", "B2"],
  ["aesthetic", "es-THET-ik", "adjective", "Concerned with beauty or the appreciation of beauty", "美的な、審美的な", "The sakura background matches the theme's aesthetic.", "B2"],
  ["whimsical", "HWIM-zi-kuhl", "adjective", "Playfully quaint or fanciful, especially in an appealing and amusing way", "気まぐれな、風変わりな", "She wrote a whimsical diary about talking pets.", "B2"],
  ["cynical", "SIN-i-kuhl", "adjective", "Believing that people are motivated by self-interest; distrustful of human sincerity", "皮肉な、冷笑的な", "He gave a cynical laugh.", "B2"],
  ["skeptical", "SKEP-ti-kuhl", "adjective", "Not easily convinced; having doubts or reservations", "懐疑的な", "I am skeptical about learning English in a week.", "B2"],
  ["stressed", "STRESD", "adjective", "Subjected to pressure or worry", "ストレスを感じる", "I was stressed about the exam.", "A2"],
  ["hyper", "HAHY-per", "adjective", "Hyperactive or unusually energetic", "興奮した", "The kids were hyper after watching the show.", "B1"],
  ["calm", "KAHM", "adjective", "Not showing or feeling nervousness, anger, or other strong emotions", "落ち着いた", "Please stay calm during the speaking test.", "A2"],
  ["peaceful", "PEES-fuhl", "adjective", "Free from disturbance; tranquil", "平和な", "The silent garden is very peaceful.", "A2"],
  ["gentle", "JEN-tl", "adjective", "Mild in temperament or behavior; kind or tender", "優しい、穏やかな", "She has a gentle character.", "A2"],
  ["hostile", "HOS-tl", "adjective", "Unfriendly; antagonistic", "敵対的な", "His behavior towards newcomers was hostile.", "B2"],
  ["friendly", "FREND-lee", "adjective", "Kind and pleasant", "友好的な", "The host was very friendly.", "A1"],
  ["nervous", "NUR-vuhs", "adjective", "Easily agitated or alarmed; apprehensive or anxious", "緊張した", "I get nervous when speaking on the phone.", "A2"],
  ["relaxed", "ri-LAKST", "adjective", "Free from tension and anxiety; at ease", "リラックスした", "He was relaxed about the quiz.", "A2"],
  ["miserable", "MIZ-er-uh-buhl", "adjective", "Wretchedly unhappy or uncomfortable", "悲惨な、惨めな", "The rainy day made me feel miserable.", "B1"],
  ["moody", "MOO-dee", "adjective", "Given to unpredictable changes of mood, especially sudden bouts of gloominess", "気分屋の", "Teenagers are often moody.", "B1"],
  ["irritable", "IR-i-tuh-buhl", "adjective", "Having or showing a tendency to be easily annoyed or made angry", "怒りっぽい", "I get irritable when I don't sleep well.", "B2"],
  ["sensitive", "SEN-si-tiv", "adjective", "Quick to detect or respond to slight changes, signals, or influences", "敏感な、傷つきやすい", "She is sensitive to criticism.", "B1"],
  ["dull", "DUHL", "adjective", "Lacking interest or excitement", "退屈な、鈍い", "The grammar sheet was a bit dull.", "B1"],
  ["excited", "ik-SAHY-tid", "adjective", "Very happy and enthusiastic", "興奮した、ワクワクした", "I am excited to start the lesson.", "A1"],
  ["boring", "BAWR-ing", "adjective", "Not interesting; tedious", "退屈な", "The lecture was boring.", "A1"],
  ["tired", "TAHY-erd", "adjective", "In need of sleep or rest; weary", "疲れた", "I was too tired to write a diary.", "A1"],
  ["exhausted", "ig-ZAW-stid", "adjective", "Very tired", "疲れ果てた", "We were exhausted after the drill.", "B1"],
  ["reluctant", "ri-LUHK-tuhnt", "adjective", "Unwilling and hesitant; disinclined", "気の進まない", "She was reluctant to read aloud.", "B2"],
  ["eager", "EE-ger", "adjective", "Strongly wanting to do or have something", "しきりに～したがる", "He is eager to speak English.", "B1"],
  ["prompt", "PROMPT", "adjective", "Done without delay; immediate", "迅速な", "I appreciate your prompt response.", "B2"],
  ["slack", "SLAK", "adjective", "Not active or busy; lazy", "怠惰な、緩い", "He has been slack with study reviews recently.", "B2"],
  ["gloomy", "GLOO-mee", "adjective", "Dark or poorly lit, especially so as to appear depressing", "薄暗い、憂鬱な", "The weather has been gloomy all week.", "B1"],
  ["elated", "ih-LEY-tid", "adjective", "Make ecstatically happy", "大喜びの", "I was elated when I earned the trophy badge.", "C1"],
  ["apathetic", "ap-uh-THET-ik", "adjective", "Showing or feeling no interest, enthusiasm, or concern", "無関心な", "He is apathetic about his exam marks.", "C1"],
  ["somber", "SOM-ber", "adjective", "Dark or dull in color or tone; gloomy", "厳かな、憂鬱な", "The background music was somber.", "B2"],
  ["cheerful", "CHEER-fuhl", "adjective", "Joyful", "楽しそうな", "A cheerful smile goes a long way.", "A2"],
  ["passionate", "PASH-uh-nit", "adjective", "Having strong feelings", "情熱のこもった", "The singer gave a passionate performance.", "B1"]
];

emotions.forEach(row => addWord(row[0], row[1], row[2], row[3], row[4], row[5], row[6], "emotions"));

// 2. daily_life (80 words)
const dailyLife = [
  ["commute", "kuh-MYOOT", "noun/verb", "To travel some distance between one's home and place of work on a regular basis", "通勤、通学", "My morning commute takes about forty minutes.", "B1"],
  ["routine", "roo-TEEN", "noun", "A sequence of actions regularly followed", "日課、ルーティン", "Studying English has become part of my daily routine.", "A2"],
  ["chore", "CHAWR", "noun", "A routine task, especially a household one", "家事、雑用", "Doing the dishes is my least favorite chore.", "B1"],
  ["deadline", "DED-lahyn", "noun", "The latest time or date by which something should be completed", "締め切り", "I must submit my diary before the midnight deadline.", "B1"],
  ["grocery", "GROH-suh-ree", "noun", "Items of food in a grocery store", "食料品、雑貨", "I went to buy groceries for dinner.", "A2"],
  ["exercise", "EK-ser-sahyz", "noun/verb", "Physical activity that is planned and structured", "運動", "It is important to exercise every day.", "A1"],
  ["schedule", "SKEJ-ool", "noun/verb", "A plan for carrying out process or procedures", "予定、スケジュール", "Let me check my schedule for tomorrow.", "A2"],
  ["appointment", "uh-POINT-muhnt", "noun", "An arrangement to meet someone at a particular time and place", "約束、予約", "I have a dentist appointment this afternoon.", "A2"],
  ["laundry", "LAWN-dree", "noun", "Clothes that need to be washed or have just been washed", "洗濯物", "I need to fold the laundry.", "A2"],
  ["recipe", "RES-uh-pee", "noun", "A set of instructions for preparing a particular dish", "レシピ、調理法", "This curry recipe is very easy to follow.", "A2"],
  ["budget", "BUHJ-it", "noun/verb", "An estimate of income and expenditure for a set period", "予算", "I am on a tight budget this month.", "B1"],
  ["habit", "HAB-it", "noun", "A settled or regular tendency or practice", "習慣", "Reading books before sleeping is a good habit.", "A2"],
  ["leisure", "LEE-zher", "noun", "Free time", "余暇、レジャー", "I like to listen to music in my leisure time.", "B1"],
  ["cleaning", "KLEEN-ing", "noun", "The action of making something clean", "掃除", "Spring cleaning takes all weekend.", "A1"],
  ["errand", "ER-uhnd", "noun", "A short journey undertaken to deliver or collect something", "お使い、雑用", "I have some errands to run in town.", "B1"],
  ["commuter", "kuh-MYOO-ter", "noun", "A person who travels some distance to work on a regular basis", "通勤者、通学者", "The train was packed with commuters.", "B2"],
  ["nap", "NAP", "noun/verb", "A short sleep, especially during the day", "昼寝", "Taking a short nap in the afternoon boosts energy.", "A2"],
  ["relax", "ri-LAKS", "verb", "Make or become less tense or anxious", "リラックスする", "Watching movie helps me relax.", "A1"],
  ["organize", "AWR-guh-nahyz", "verb", "Arrange into a structured whole; order", "整理する、組織する", "I need to organize my study materials.", "B1"],
  ["multitask", "muhl-tee-TASK", "verb", "Perform more than one task at the same time", "マルチタスクをする", "It is hard to multitask while studying.", "B2"],
  ["productivity", "proh-duhk-TIV-i-tee", "noun", "The state or quality of being productive", "生産性", "A tidy desk improves productivity.", "B2"],
  ["journal", "JUR-nl", "noun/verb", "A daily record of news and events of a personal nature", "日記、ジャーナル", "I write in my journal every night.", "B1"],
  ["clutter", "KLUHT-er", "noun/verb", "A collection of things lying about in an untidy mass", "散らかり、がらくた", "I need to clear the clutter from my room.", "B2"],
  ["decor", "dey-KAWR", "noun", "The decoration of a room", "室内装飾、デコレーション", "She prefers a simple Japanese decor.", "B2"],
  ["renovation", "ren-uh-VEY-shuhn", "noun", "The action of renovating a building", "リノベーション、修復", "Our house is under renovation.", "B2"],
  ["neighborhood", "NEY-ber-hood", "noun", "A district, especially one forming a community", "近所、地域", "This neighborhood is very quiet.", "A2"],
  ["tenant", "TEN-uhnt", "noun", "A person who occupies land or property rented from a landlord", "店借人、テナント", "The tenant in the room next door is friendly.", "B2"],
  ["landlord", "LAND-lawrd", "noun", "A person, especially a man, who rents land, a building, or an apartment", "大家さん", "Our landlord is very understanding.", "B1"],
  ["household", "HOWS-hohld", "noun/adjective", "A house and its occupants regarded as a unit", "世帯、家庭の", "We share household bills.", "B1"],
  ["suburb", "SUHB-urb", "noun", "An outlying district of a city, especially a residential one", "郊外", "I live in a peaceful suburb.", "B1"],
  ["maintenance", "MEYN-tuh-nuhns", "noun", "The process of maintaining or preserving someone or something", "メンテナンス、維持", "Car maintenance can be expensive.", "B2"],
  ["appliance", "uh-PLAHY-uhns", "noun", "A device or piece of equipment designed to perform a specific task", "家電製品", "The kitchen appliances are brand new.", "B1"],
  ["utility", "yoo-TIL-i-tee", "noun", "The state of being useful, profitable, or beneficial", "公共料金、公益事業", "Water and electricity are basic utilities.", "B2"],
  ["rent", "RENT", "noun/verb", "A tenant's regular payment to a landlord for the use of property", "家賃、賃貸する", "The rent is due on the first of the month.", "A2"],
  ["lease", "LEES", "noun/verb", "A contract by which one party conveys land, property, services, etc.", "リース、賃貸契約", "We signed a one-year lease.", "B2"],
  ["mortgage", "MAWR-gij", "noun/verb", "A legal agreement by which a bank lends money at interest", "住宅ローン", "Paying off the mortgage takes thirty years.", "B2"],
  ["cozy", "KOH-zee", "adjective", "Giving a feeling of comfort, warmth, and relaxation", "居心地の良い", "The small cafe felt very cozy.", "A2"],
  ["spacious", "SPEY-shuhs", "adjective", "Having ample space", "広々とした", "Her new apartment is spacious.", "B1"],
  ["cluttered", "KLUHT-erd", "adjective", "Untidy", "散らかった", "His desk was cluttered with papers.", "B1"],
  ["tidy", "TAHY-dee", "adjective/verb", "Arranged neatly and in order", "きれいな、片付ける", "She keeps her room tidy.", "A2"],
  ["messy", "MES-ee", "adjective", "Untidy or dirty", "散らかった、汚い", "The kitchen was messy after cooking.", "A2"],
  ["orderly", "AWR-der-lee", "adjective", "Neatly and methodically arranged", "整然とした", "Students stood in an orderly line.", "B2"],
  ["domestic", "duh-MES-tik", "adjective", "Relating to the running of a home or to family relations", "家庭の、国内の", "Domestic chores can be shared.", "B1"],
  ["convenient", "kuhn-VEEN-yuhnt", "adjective", "Fitting in well with a person's needs, activities, and plans", "便利な", "The convenience store is very convenient.", "B1"],
  ["tasty", "TEYS-tee", "adjective", "Having a pleasant, distinct flavor", "おいしい", "This soup is very tasty.", "A1"],
  ["nutritious", "noo-TRISH-uhs", "adjective", "Efficient as a food; nourishing", "栄養のある", "Homemade meals are nutritious.", "B1"],
  ["refreshing", "ri-FRESH-ing", "adjective", "Serving to refresh", "爽快な、リフレッシュさせる", "A cold drink is refreshing in summer.", "B1"],
  ["exhausting", "ig-ZAWS-ting", "adjective", "Making one feel very tired", "疲れさせる", "Cleaning the whole house was exhausting.", "B1"],
  ["hectic", "HEK-tik", "adjective", "Full of incessant or frantic activity", "大忙しの、てんてこ舞いの", "The schedule was hectic today.", "B2"],
  ["monotonous", "muh-NOT-n-uhs", "adjective", "Dull, tedious, and repetitious; lacking in variety and interest", "単調な", "The routine was monotonous.", "B2"],
  ["tiresome", "TAHY-er-suhm", "adjective", "Causing one to feel bored or annoyed", "退屈な、うんざりする", "Repetitive tasks are tiresome.", "B2"],
  ["pleasant", "PLEZ-uhnt", "adjective", "Giving a sense of happy satisfaction or enjoyment", "心地よい", "The evening breeze was pleasant.", "B1"],
  ["unpleasant", "uhn-PLEZ-uhnt", "adjective", "Not pleasant", "不快な", "The smell was unpleasant.", "B1"],
  ["daily", "DEY-lee", "adjective/adverb", "Every day", "日々の", "This is our daily quiz.", "A1"],
  ["weekly", "WEEK-lee", "adjective/adverb", "Every week", "週刊の", "He sends a weekly report.", "A2"],
  ["monthly", "MUHNTH-lee", "adjective/adverb", "Every month", "月刊の", "Our rent is a monthly payment.", "A2"],
  ["annual", "AN-yoo-uhl", "adjective", "Occurring once every year", "年次の、年に一度の", "We have our annual review next week.", "B1"],
  ["regular", "REG-yuh-ler", "adjective", "Done or happening frequently", "規則的な、通常の", "I have regular lessons.", "A2"],
  ["occasional", "uh-KEY-zhuh-nl", "adjective", "Occurring, appearing, or done infrequently and irregularly", "たまの、時々の", "I enjoy an occasional cup of coffee.", "B1"],
  ["frequent", "FREE-kwuhnt", "adjective", "Occurring or done on many occasions", "頻繁な", "Frequent practice leads to fluency.", "B1"],
  ["rare", "RAIR", "adjective", "Not occurring, found, or experienced frequently", "稀な", "It is rare to see snow here.", "B1"],
  ["constant", "KON-stuhnt", "adjective", "Occurring continuously over a period of time", "一定の、絶え間ない", "Constant review helps memory.", "B1"],
  ["temporary", "TEM-puh-rer-ee", "adjective", "Lasting for only a limited period of time", "一時的な", "The library cards are temporary.", "B1"],
  ["permanent", "PUR-muh-nuhnt", "adjective", "Lasting or intended to last or remain unchanged indefinitely", "恒久的な", "The notes page is permanent.", "B1"],
  ["essential", "ih-SEN-shuhl", "adjective", "Absolutely necessary; extremely important", "不可欠な、不可欠の", "A dictionary is essential.", "B1"],
  ["optional", "OP-shuh-nl", "adjective", "Available to be chosen but not obligatory", "オプションの、任意の", "Subtitles are optional in listening.", "B1"],
  ["urgent", "UR-juhnt", "adjective", "Requiring immediate action or attention", "緊急の", "This is an urgent homework assignment.", "B1"],
  ["trivial", "TRIV-ee-uhl", "adjective", "Of little value or importance", "些細な", "Don't worry about trivial spelling slips.", "B2"],
  ["significant", "sig-NIF-i-kuhnt", "adjective", "Sufficiently great or important to be worthy of attention", "重要な、著しい", "He showed significant improvement.", "B1"],
  ["minor", "MAHY-ner", "adjective", "Lesser in importance, seriousness, or significance", "マイナーな、軽微な", "There was a minor mistake in pronunciation.", "A2"],
  ["major", "MEY-jer", "adjective", "Important, serious, or significant", "主要な、重大な", "There is a major update coming.", "A2"],
  ["standard", "STAN-derd", "noun/adjective", "Used or accepted as normal or average", "標準の", "Standard English is taught here.", "A2"],
  ["exceptional", "ik-SEP-shuh-nl", "adjective", "Unusually good; outstanding", "例外的な、非常に優れた", "Her writing progress was exceptional.", "B2"],
  ["adequate", "AD-i-kwit", "adjective", "Satisfactory or acceptable in quality or quantity", "十分な", "His response was adequate.", "B2"],
  ["inadequate", "in-AD-i-kwit", "adjective", "Lacking the quality or quantity required", "不十分な", "The study time was inadequate.", "B2"],
  ["custom", "KUHS-tuhm", "adjective/noun", "Made or done to order", "カスタムの、特別注文の", "We built a custom note widget.", "B1"],
  ["traditional", "truh-DISH-uh-nuhl", "adjective", "Existing in or as part of a tradition", "伝統的な", "We study traditional vocabulary.", "B1"],
  ["modern", "MOD-ern", "adjective", "Relating to the present or recent times", "現代の", "Modern slang is interesting.", "A2"],
  ["ancient", "EYN-shuhnt", "adjective", "Belonging to the very distant past", "古代の", "They studied ancient literature.", "B1"],
  ["future", "FYOO-cher", "noun/adjective", "A period of time following the moment of speaking", "未来の", "My future plans include study abroad.", "A1"]
];

dailyLife.forEach(row => addWord(row[0], row[1], row[2], row[3], row[4], row[5], row[6], "daily_life"));

// 3. anime (60 words)
const anime = [
  ["protagonist", "proh-TAG-uh-nist", "noun", "The leading character or one of the major characters in a drama, movie, novel, or other fictional text", "主人公", "The protagonist in that anime is very determined.", "B2"],
  ["antagonist", "an-TAG-uh-nist", "noun", "A person who actively opposes or is hostile to someone or something", "悪役、対立者", "A strong antagonist makes the plot interesting.", "B2"],
  ["foreshadowing", "fawr-SHAD-oh-ing", "noun", "A warning or indication of a future event", "伏線", "The early scenes have subtle foreshadowing.", "B2"],
  ["cliffhanger", "KLIF-hang-er", "noun", "An ending to an episode of a serial drama that leaves the audience in suspense", "崖っぷち、クリフハンガー（次回への焦らし）", "Every episode ends on a cliffhanger.", "B1"],
  ["redemption", "ri-DEMP-shuhn", "noun", "The action of saving or being saved from sin, error, or evil", "救済、贖罪", "The villain's redemption arc was emotional.", "B2"],
  ["narrator", "NAR-ey-ter", "noun", "A person who narrates something, especially a character who recounts the events of a novel or narrative poem", "ナレーター", "The narrator explained the backstory.", "B2"],
  ["subtitles", "SUB-tahy-tlz", "noun", "Captions displayed at the bottom of a cinema or television screen", "字幕", "I watch anime with English subtitles.", "A2"],
  ["animation", "an-uh-MEY-shuhn", "noun", "The technique of photographing successive drawings or positions of puppets or models", "アニメーション", "The animation quality was stunning.", "A2"],
  ["manga", "MAHNG-guh", "noun", "A style of Japanese comic books and graphic novels", "漫画", "I read the manga before watching the show.", "A1"],
  ["fandom", "FAN-duhm", "noun", "The fans of a particular person, team, fictional series, etc. regarded collectively as a community", "ファンダム、ファン界隈", "The anime fandom is very active on internet.", "B2"],
  ["spinoff", "SPIN-awf", "noun", "A byproduct or incidental result of a larger project", "スピンオフ、番外編", "The spinoff series focuses on his childhood.", "B1"],
  ["sequel", "SEE-kwuhl", "noun", "A published, broadcast, or recorded work that continues the story of an earlier one", "続編", "I am eagerly waiting for the sequel.", "B1"],
  ["prequel", "PREE-kwuhl", "noun", "A story or movie containing events that precede those of an existing work", "前日譚", "The prequel explained the origin of the powers.", "B2"],
  ["adaptation", "ad-uhp-TEY-shuhn", "noun", "A movie, television drama, or play that has been adapted from a written work", "実写化、適応", "The live-action adaptation was disappointing.", "B2"],
  ["crossover", "KRAWS-oh-ver", "noun", "A point or place of crossing from one side, road, or track to another", "クロスオーバー、コラボ", "The crossover episode featured characters from two shows.", "B1"],
  ["genre", "ZHAHN-ruh", "noun", "A category of artistic composition", "ジャンル", "Fantasy is my favorite anime genre.", "B1"],
  ["dubbing", "DUHB-ing", "noun", "The replacement of the original speech in a cinema or television show with speech in another language", "吹き替え", "I prefer dubbing over subtitles sometimes.", "B1"],
  ["episode", "EP-uh-sohd", "noun", "An event or a group of events occurring as part of a larger sequence", "エピソード、第１話", "The latest episode was wild.", "A2"],
  ["season", "SEE-zuhn", "noun", "A set of program broadcasts", "シーズン", "Season three starts next month.", "A2"],
  ["merchandise", "MUR-chuhn-dahyz", "noun/verb", "Goods to be bought and sold", "グッズ、商品", "I bought some anime merchandise.", "B2"],
  ["cosplay", "KOZ-pley", "noun/verb", "The practice of dressing up as a character from a movie, book, or video game", "コスプレ", "She does amazing cosplay.", "B1"],
  ["voiceover", "VOIS-oh-ver", "noun", "A piece of narration in a movie or broadcast, not accompanied by an image of the speaker", "ボイスオーバー", "The voiceover actor has a deep voice.", "B1"],
  ["canon", "KAN-uhn", "noun", "The works of a particular author or artist that are accepted as genuine", "公式設定、原作通り", "That episode is not canon; it's just filler.", "B2"],
  ["filler", "FIL-er", "noun", "An item or substance used to fill a space or container", "引き延ばし回、フィラー", "I skipped the filler episodes.", "B1"],
  ["cliche", "klee-SHEY", "noun/adjective", "A phrase or opinion that is overused and betrays a lack of original thought", "お決まりのパターン、使い古された表現", "The power of friendship is an anime cliche.", "B2"],
  ["spoiler", "SPOI-ler", "noun", "A description of an important plot development in a television show, movie, or book which, if known beforehand, may reduce the interest", "ネタバレ", "Please don't tell me any spoilers.", "B1"],
  ["fanfiction", "FAN-fik-shuhn", "noun", "Fiction written by a fan of, and featuring characters from, a particular TV series, movie, etc.", "二次創作、二次小説", "She writes fanfiction in her free time.", "B2"],
  ["premiere", "pri-MEER", "noun/verb", "The first performance of a musical or theatrical work or the first showing of a movie", "プレミア上映、初公開", "The movie premiere was crowded.", "B2"],
  ["otaku", "oh-TAH-koo", "noun", "A young person who is obsessed with computers or particular aspects of popular culture", "オタク", "He is proud to be an otaku.", "B1"],
  ["dialogue", "DAHY-uh-lawg", "noun", "Conversation between two or more people", "対話、台詞", "The dialogue in that scene was moving.", "B1"],
  ["monologue", "MON-uh-lawg", "noun", "A long speech by one actor in a play or movie", "独白、モノローグ", "His inner monologue revealed his fear.", "B2"],
  ["backstory", "BAK-staw-ree", "noun", "A history or background, especially one created for a fictional character in a novel or play", "背景、過去の経歴", "The hero has a tragic backstory.", "B2"],
  ["visuals", "VIZH-oo-uhlz", "noun", "A picture, piece of film, or display used to accompany or illustrate something", "映像美、ビジュアル", "The visuals in this movie are breathtaking.", "B1"],
  ["universe", "YOO-nuh-vurs", "noun", "A particular sphere of activity or experience", "世界観、宇宙", "The characters exist in a parallel universe.", "B1"],
  ["franchise", "FRAN-chahyz", "noun/verb", "An authorization granted by a government or company to an individual or group", "シリーズ、フランチャイズ", "This franchise has three movies.", "B2"],
  ["tribute", "TRIB-yoot", "noun", "An act, statement, or gift that is intended to show gratitude, respect, or admiration", "オマージュ、賛辞", "The scene was a tribute to classic films.", "B2"],
  ["villain", "VIL-uhn", "noun", "A character whose evil actions or motives are important to the plot", "悪役", "The villain had a complex motive.", "B1"],
  ["hero", "HEE-roh", "noun", "A person who is admired or idealized for their courage, outstanding achievements, or noble qualities", "ヒーロー", "Every hero needs a challenge.", "A1"],
  ["rival", "RAHY-vuhl", "noun/verb", "A person or thing competing with another for the same objective or for superiority in the same field", "ライバル", "The protagonist and his rival trained together.", "B1"],
  ["mentor", "MEN-tawr", "noun/verb", "An experienced and trusted adviser", "指導者、メンター", "The old master was his mentor.", "B2"],
  ["dynamic", "dahy-NAM-ik", "adjective", "Constantly changing", "躍動的な、ダイナミックな", "The battle scenes were dynamic.", "B2"],
  ["artistic", "ahr-TIS-tik", "adjective", "Having or revealing natural creative skill", "芸術的な", "The background art was very artistic.", "B1"],
  ["legendary", "LEJ-uhn-der-ee", "adjective", "Remarkable enough to be famous; very well known", "伝説の", "The legendary hero vanished.", "B1"],
  ["mysterious", "mi-STEER-ee-uhs", "adjective", "Difficult or impossible to understand, explain, or identify", "神秘的な、謎めいた", "A mysterious character appeared.", "B1"],
  ["fictional", "FIK-shuh-nl", "adjective", "Relating to, or occurring in fiction; invented", "架空の、フィクションの", "The story is set in a fictional town.", "B1"],
  ["authentic", "aw-THEN-tik", "adjective", "Of undisputed origin; genuine", "本物の、信頼できる", "The sword replica looks authentic.", "B2"],
  ["filler", "FIL-er", "adjective/noun", "Extra content", "本筋に関係ない内容", "That was just a filler chapter.", "B1"],
  ["original", "uh-RIJ-uh-nl", "adjective/noun", "Present or existing from the beginning", "オリジナルの、独創的な", "The original creator approved this.", "A2"],
  ["stunning", "STUHN-ing", "adjective", "Extremely impressive or attractive", "見事な、息をのむような", "The graphics are stunning.", "B2"],
  ["dramatic", "druh-MAT-ik", "adjective", "Sudden and striking", "劇的な、ドラマチックな", "There was a dramatic plot change.", "B1"],
  ["intense", "in-TENS", "adjective", "Of extreme force, degree, or strength", "激しい、強烈な", "The battle was intense.", "B1"],
  ["epic", "EP-ik", "adjective/noun", "Heroic or grand in scale", "壮大な、叙事詩的な", "The final battle was epic.", "B1"],
  ["classic", "KLAS-ik", "adjective/noun", "Judged over a period of time to be of the highest quality and outstanding of its kind", "古典的な、名作の", "That is a classic anime show.", "B1"],
  ["clumsy", "KLUHM-zee", "adjective", "Awkward in movement or in handling things", "ドジな、不器用な", "The protagonist's sidekick is clumsy.", "B1"],
  ["quirky", "KWUR-kee", "adjective", "Characterized by peculiar or unexpected traits", "一風変わった", "The characters are very quirky.", "B2"],
  ["charming", "CHAHR-ming", "adjective", "Pleasant or attractive", "チャーミングな", "The slice-of-life scenes are charming.", "B1"],
  ["iconic", "ahy-KON-ik", "adjective", "Relating to or of the nature of an icon", "象徴的な、アイコニックな", "The character's pose is iconic.", "B2"],
  ["overpowered", "oh-ver-POW-erd", "adjective", "Defeat by greater strength", "強すぎる、チート級の", "The protagonist is completely overpowered.", "B2"],
  ["underrated", "uhn-der-REY-tid", "adjective", "Underestimated in value", "過小評価された", "This hidden gem anime is underrated.", "B2"],
  ["overrated", "oh-ver-REY-tid", "adjective", "Rated too highly", "過大評価された", "Honestly, that show is overrated.", "B2"]
];

anime.forEach(row => addWord(row[0], row[1], row[2], row[3], row[4], row[5], row[6], "anime"));

// 4. music (60 words)
const music = [
  ["lyrics", "LIR-iks", "noun", "The words of a song", "歌詞", "I wrote down the lyrics of my favorite song.", "A2"],
  ["chorus", "KAWR-uhs", "noun", "A part of a song that is repeated after each verse", "コーラス、サビ", "The chorus is very catchy.", "B1"],
  ["melody", "MEL-uh-dee", "noun", "A sequence of single notes that is musically satisfying", "メロディー、旋律", "The piano melody is beautiful.", "A2"],
  ["rhythm", "RITH-uhm", "noun", "A strong, regular, repeated pattern of movement or sound", "リズム", "He clapped to the rhythm of the beat.", "B1"],
  ["vibrato", "vi-BRAH-toh", "noun", "A rapid, slight variation in pitch in singing or playing some instruments", "ビブラート", "Her voice has a natural vibrato.", "C1"],
  ["acoustic", "uh-KOO-stik", "adjective", "Relating to sound or the sense of hearing", "アコースティック、生音の", "I prefer the acoustic version of the track.", "B1"],
  ["soulful", "SOHL-fuhl", "adjective", "Expressing or appearing to express deep and often sorrowful feeling", "魂のこもった、感情豊かな", "His vocals were soulful and moving.", "B2"],
  ["harmony", "HAHR-muh-nee", "noun", "The combination of simultaneously sounded musical notes to produce chords", "ハーモニー、調和", "Their voices matched in perfect harmony.", "B1"],
  ["composer", "kuhn-POH-zer", "noun", "A person who writes music, especially as a professional occupation", "作曲家", "The anime soundtrack composer is famous.", "B1"],
  ["instrument", "IN-struh-muhnt", "noun", "An object or device for producing musical sounds", "楽器", "The violin is a difficult instrument.", "A2"],
  ["recital", "ri-SAHY-tl", "noun", "A performance of program of music", "リサイタル、発表会", "I attended my friend's piano recital.", "B2"],
  ["concert", "KON-surt", "noun", "A musical performance given in public", "コンサート", "We went to an outdoor concert.", "A1"],
  ["track", "TRAK", "noun", "A recording of one song or piece of music", "トラック、楽曲", "Skip to the next track.", "A2"],
  ["album", "AL-buhm", "noun", "A collection of audio recordings issued as a single item", "アルバム", "Their debut album sold out.", "A2"],
  ["playlist", "PLAY-list", "noun", "A list of recorded songs or pieces of music", "プレイリスト", "I added Clairo's song to my playlist.", "A1"],
  ["tempo", "TEM-poh", "noun", "The speed at which a passage of music is or should be played", "テンポ", "The song has a fast tempo.", "B1"],
  ["lyrics", "LIR-iks", "noun/adjective", "The words of a song", "歌詞の、叙情的な", "She enjoys writing lyrical journals.", "B2"],
  ["vocals", "VOH-kuhlz", "noun", "The part of a piece of music that is sung", "ボーカル", "The vocals were clear and loud.", "B1"],
  ["refrain", "ri-FRAYN", "noun/verb", "A repeated line or number of lines in a poem or song", "リフレイン、繰り返しの句", "The refrain echoed in my mind.", "B2"],
  ["beat", "BEET", "noun/verb", "A main accent or rhythmic unit in music or poetry", "ビート、拍子", "The crowd danced to the beat.", "A2"],
  ["genre", "ZHAHN-ruh", "noun", "A category", "音楽ジャンル", "Lofi beats is a popular genre for studying.", "B1"],
  ["duet", "doo-ET", "noun", "A performance by two singers or instrumentalists", "デュエット、二重奏", "They sang a romantic duet.", "B1"],
  ["solo", "SOH-loh", "noun/adjective", "A piece of music for one voice or instrument", "ソロ、単独の", "The guitarist played an epic solo.", "A2"],
  ["bass", "BEYS", "noun/adjective", "The lowest adult male singing voice", "ベース、低音の", "Turn up the bass on the speaker.", "B1"],
  ["treble", "TREB-uhl", "noun/adjective", "The highest voice or part in cooperative singing", "高音の、トレブル", "The treble was a bit too high.", "B2"],
  ["amplifier", "AM-pluh-fahy-er", "noun", "An electronic device for increasing the amplitude of electrical signals, used in sound reproduction", "アンプ、増幅器", "Connect the guitar to the amplifier.", "B2"],
  ["chord", "KAWRD", "noun", "A group of notes sounded together as a basis of harmony", "コード、和音", "He learned three basic guitar chords.", "B1"],
  ["tune", "TOON", "noun/verb", "A melody, especially a simple and easily remembered one", "曲、チューニングする", "I hummed a familiar tune.", "A2"],
  ["synth", "SINTH", "noun", "A synthesizer", "シンセサイザー", "The track features a futuristic synth beat.", "B2"],
  ["reverb", "ri-VURB", "noun", "An effect whereby the sound produced by an amplifier or an acoustic instrument is made to reverberate", "リバーブ、残響", "The vocals had a lot of reverb.", "C1"],
  ["echo", "EK-oh", "noun/verb", "A sound or series of sounds caused by the reflection of sound waves", "エコー、こだま", "My voice echoed in the empty hall.", "B1"],
  ["resonance", "REZ-uh-nuhns", "noun", "The quality in a sound of being deep, full, and reverberating", "響き、レゾナンス", "Her voice had a deep resonance.", "C1"],
  ["pitch", "PICH", "noun/verb", "The quality of a sound governed by the rate of vibrations producing it", "音高、ピッチ", "His pitch was slightly off.", "B1"],
  ["key", "KEE", "noun", "A system of notes", "キー、調", "This song is in the key of C major.", "A1"],
  ["scale", "SKEYL", "noun", "A graduated sequence of notes", "音階、スケール", "The student practiced the major scale.", "B1"],
  ["performance", "per-FAWR-muhns", "noun", "An act of staging or presenting a play, concert, or other form of entertainment", "パフォーマンス、演奏", "Her live performance was outstanding.", "A2"],
  ["instrumental", "in-struh-MEN-tl", "adjective/noun", "Serving as a means of pursuing something", "インストゥルメンタル、歌詞のない", "I study best with instrumental music.", "B1"],
  ["live", "LAHYV", "adjective/adverb", "Broadcast, recorded, or performed at the time of occurrence", "ライブの、生演奏の", "They went to a live show.", "A2"],
  ["studio", "STOO-dee-oh", "noun", "A room where an artist, photographer, sculptor, etc. works", "録音スタジオ", "The band recorded in a professional studio.", "A2"],
  ["producer", "pruh-DOO-ser", "noun", "A person, company, or country that makes, grows, or supplies goods or commodities for sale", "プロデューサー", "The music producer helped mix the track.", "B2"],
  ["catchy", "KACH-ee", "adjective", "Instantly appealing and memorable", "キャッチーな、耳に残る", "The chorus is so catchy.", "B1"],
  ["melodic", "muh-LOD-ik", "adjective", "Of, having, or producing melody", "旋律的な、メロディアスな", "The pop track was very melodic.", "B2"],
  ["rhythmic", "RITH-mik", "adjective", "Having or relating to rhythm", "リズムに乗った", "The rhythmic clapping filled the hall.", "B2"],
  ["tuneful", "TOON-fuhl", "adjective", "Having a pleasing tune", "調べの美しい", "She wrote a tuneful melody.", "B2"],
  ["acoustic", "uh-KOO-stik", "adjective/noun", "Unplugged", "アコースティック楽器の", "The singer played an acoustic guitar.", "B1"],
  ["harmony", "HAHR-muh-nee", "adjective/noun", "Pleasing combo", "調和した", "The backing vocals were in harmony.", "B1"],
  ["vocal", "VOH-kuhl", "adjective/noun", "Singing", "ボーカルの、声を大にする", "She took vocal lessons.", "B1"],
  ["soothing", "SOOTH-ing", "adjective", "Having a gently calming effect", "心地よい、なだめるような", "Soft jazz is very soothing.", "B1"],
  ["energetic", "en-er-JET-ik", "adjective", "Showing or involving great activity or vitality", "活動的な、元気な", "The beat was energetic.", "B1"],
  ["monotonous", "muh-NOT-n-uhs", "adjective/noun", "Repetitive sound", "一本調子の", "The drum beat was monotonous.", "B2"],
  ["noisy", "NOI-zee", "adjective", "Making a lot of noise", "騒がしい", "The club was noisy.", "A1"],
  ["silent", "SAHY-luhnt", "adjective", "Not making or accompanied by any sound", "静かな", "The room fell silent.", "A2"],
  ["loud", "LOWD", "adjective/adverb", "Producing a lot of change", "うるさい、大音量の", "The volume was too loud.", "A1"],
  ["soft", "SAWFT", "adjective/adverb", "Quiet and gentle", "静かな、柔らかな", "The background music was soft.", "A1"],
  ["dynamic", "dahy-NAM-ik", "adjective/noun", "Volume variation", "強弱のある", "The classical track has a dynamic range.", "B2"],
  ["soulful", "SOHL-fuhl", "adjective/noun", "Deeply emotional", "ソウルフルな", "She sang a soulful ballad.", "B2"],
  ["melancholy", "MEL-an-kol-ee", "adjective/noun", "Sad song style", "哀愁を帯びた", "Lofi tracks often have a melancholy vibe.", "B2"],
  ["upbeat", "UHP-beet", "adjective/noun", "Cheerful; optimistic", "テンポの速い、陽気な", "The song has an upbeat tempo.", "B1"],
  ["classic", "KLAS-ik", "adjective/noun", "Old standard", "クラシック音楽の", "He likes classical music.", "A2"],
  ["modern", "MOD-ern", "adjective/noun", "New style", "現代風の", "Modern pop mixes synths.", "A2"]
];

music.forEach(row => addWord(row[0], row[1], row[2], row[3], row[4], row[5], row[6], "music"));

// 5. nature (50 words)
const nature = [
  ["blossom", "BLOS-uhm", "noun/verb", "A flower or a mass of flowers on a tree or bush", "花、開花する", "The cherry blossoms look beautiful in spring.", "B1"],
  ["foliage", "FOH-lee-ij", "noun", "Plant leaves collectively", "葉、紅葉", "Autumn foliage turns the mountains orange and gold.", "C1"],
  ["scenery", "SEEN-uh-ree", "noun", "The natural features of a landscape considered in terms of their appearance", "景色、風光", "The train route offers beautiful mountain scenery.", "A2"],
  ["breeze", "BREEZ", "noun", "A gentle wind", "微風、そよ風", "A cool evening breeze blew through the window.", "A2"],
  ["tranquil", "TRANG-kwil", "adjective", "Free from disturbance; calm", "穏やかな、閑静な", "The lake was tranquil in the morning.", "B2"],
  ["drizzle", "DRIZ-uhl", "noun/verb", "Light rain falling in very fine drops", "霧雨、しとしと降る雨", "It was just a light drizzle, so we didn't open umbrellas.", "B1"],
  ["wilderness", "WIL-der-nis", "noun", "An uncultivated, uninhabited, and inhospitable region", "荒野、大自然", "Hiking in the wilderness requires a map.", "B2"],
  ["canopy", "KAN-uh-pee", "noun", "An ornamental cloth-like covering", "林冠、キャノピー（木々の覆い）", "We walked under the green forest canopy.", "C1"],
  ["landscape", "LAND-skeyp", "noun/verb", "All the visible features of an area of countryside or land", "風景、ランドスケープ", "The landscape was covered in deep snow.", "B1"],
  ["climate", "KLAHY-mit", "noun", "The weather conditions prevailing in an area", "気候", "Japan has a temperate climate with four seasons.", "A2"],
  ["season", "SEE-zuhn", "noun", "Each of the four divisions of the year", "季節", "Spring is my favorite season.", "A1"],
  ["horizon", "huh-RAHY-zuhn", "noun", "The line at which the earth's surface and the sky appear to meet", "地平線、水平線", "The sun sank below the horizon.", "B1"],
  ["meadow", "MED-oh", "noun", "A piece of grassland", "牧草地、草原", "The meadow was filled with yellow flowers.", "B1"],
  ["stream", "STREEM", "noun/verb", "A small, narrow river", "小川", "A clear stream flows near the cottage.", "A2"],
  ["valley", "VAL-ee", "noun", "A low area of land between hills or mountains", "谷", "The village is nestled in a valley.", "A2"],
  ["summit", "SUHM-it", "noun", "The highest point of a hill or mountain", "山頂、首脳会談", "It took five hours to reach the summit.", "B2"],
  ["glacier", "GLEY-sher", "noun", "A slowly moving mass or river of ice", "氷河", "The glacier is melting due to climate change.", "B2"],
  ["monsoon", "mon-SOON", "noun", "A seasonal wind in the region of South and Southeast Asia", "モンスーン、梅雨", "The summer monsoon brings heavy rain.", "B2"],
  ["drought", "DROWT", "noun", "A prolonged period of abnormally low rainfall", "干ばつ", "The lack of rain caused a severe drought.", "B2"],
  ["thunderstorm", "THUHN-der-stawrm", "noun", "A storm with thunder and lightning and typically also heavy rain", "雷雨", "A sudden thunderstorm cancelled our picnic.", "A2"],
  ["avalanche", "AV-uh-lanch", "noun/verb", "A mass of snow, ice, and rocks falling rapidly down a mountainside", "雪崩", "The road was closed due to an avalanche hazard.", "B2"],
  ["earthquake", "URTH-kweyk", "noun", "A sudden and violent shaking of the ground", "地震", "Japan experiences frequent minor earthquakes.", "A2"],
  ["eruption", "ih-RUHP-shuhn", "noun", "An act of erupting", "噴火", "The volcanic eruption sent ash into the sky.", "B2"],
  ["biodiversity", "bahy-oh-dih-VUR-si-tee", "noun", "The variety of life in the world or in a particular habitat or ecosystem", "生物多様性", "Rainforests are rich in biodiversity.", "C1"],
  ["eco-friendly", "EE-koh-frend-lee", "adjective", "Not harmful to the environment", "環境に優しい", "Using a reusable bottle is eco-friendly.", "B1"],
  ["environment", "en-VAHY-ruhn-muhnt", "noun", "The surroundings or conditions in which a person, animal, or plant lives", "環境", "We must protect the natural environment.", "B1"],
  ["conservation", "kon-ser-VEY-shuhn", "noun", "The action of conserving something", "保全、環境保護", "Water conservation is important in summer.", "B2"],
  ["habitat", "HAB-i-tat", "noun", "The natural home or environment of an animal, plant, or other organism", "生息地", "Forest destruction threatens wild animal habitats.", "B2"],
  ["ecosystem", "EE-koh-sis-tuhm", "noun", "A biological community of interacting organisms and their physical environment", "生態系", "Every creature plays a part in the ecosystem.", "B2"],
  ["pollution", "puh-LOO-shuhn", "noun", "The presence in or introduction into the environment of a substance or thing that has harmful effects", "汚染", "Air pollution is a major issue in big cities.", "B1"],
  ["lush", "LUHSH", "adjective", "Growing luxuriantly", "青々と茂った", "The valley was lush and green.", "B2"],
  ["barren", "BAR-uhn", "adjective", "Too poor to produce much or any vegetation", "不毛の、荒涼とした", "The desert was a barren landscape.", "B2"],
  ["scenic", "SEEN-ik", "adjective", "Providing or relating to views of impressive natural scenery", "景色の良い", "We took the scenic route.", "B1"],
  ["rugged", "RUHG-id", "adjective", "Having a broken, rocky, and uneven surface", "険しい、ゴツゴツした", "The hikers climbed the rugged cliffs.", "B2"],
  ["muddy", "MUHD-ee", "adjective", "Covered in or full of mud", "泥だらけの", "The path was muddy after the rain.", "A2"],
  ["clear", "KLEER", "adjective", "Easy to perceive, understand, or interpret", "晴れ渡った、透明な", "The sky was clear and blue.", "A1"],
  ["cloudy", "KLOW-dee", "adjective", "Full of or covered with clouds", "曇りの", "It was a cloudy afternoon.", "A1"],
  ["misty", "MIS-tee", "adjective", "Full of, covered with, or accompanied by mist", "霧のかかった", "The valley looked misty in the morning.", "B1"],
  ["foggy", "FOG-ee", "adjective", "Full of or characterized by fog", "霧の濃い", "It is dangerous to drive in foggy weather.", "A2"],
  ["humid", "HYOO-mid", "adjective", "Marked by a relatively high level of water vapor in the atmosphere", "湿気のある、蒸し暑い", "Summer in Tokyo is very humid.", "B1"],
  ["temperate", "TEM-per-it", "adjective", "Relating to or denoting a region or climate characterized by mild temperatures", "温帯の、穏やかな", "We enjoy a temperate climate.", "B2"],
  ["tropical", "TROP-i-kuhl", "adjective", "Resembling conditions in the tropics", "熱帯の", "Tropical forests have many species.", "B1"],
  ["polar", "POH-ler", "adjective", "Relating to the North or South Pole", "極地の", "Polar bears live in freezing conditions.", "B1"],
  ["natural", "NACH-er-uhl", "adjective", "Existing in or caused by nature", "自然の", "I like natural ingredients.", "A1"],
  ["wild", "WAHYLD", "adjective", "Living or growing in the natural environment", "野生の、野生の", "There are wild deer in Nara.", "A2"],
  ["domestic", "duh-MES-tik", "adjective", "Tame", "飼いならされた", "Cats are domestic animals.", "B1"],
  ["fertile", "FUR-tl", "adjective", "Producing or capable of producing abundant vegetation or crops", "肥沃な", "The river valley has fertile soil.", "B2"],
  ["organic", "awr-GAN-ik", "adjective", "Relating to or derived from living matter", "有機的な、オーガニックの", "We buy organic vegetables.", "B1"],
  ["coastal", "KOHS-tuhl", "adjective", "Of or near a coast", "沿岸の", "They took a walk along the coastal path.", "B1"],
  ["mountainous", "MOUN-tuh-nuhs", "adjective", "Having many mountains", "山がちな", "Japan is a mountainous country.", "B1"]
];

nature.forEach(row => addWord(row[0], row[1], row[2], row[3], row[4], row[5], row[6], "nature"));

// 6. food (50 words)
const food = [
  ["savory", "SEY-vuh-ree", "adjective", "Belonging to the category that is salty or spicy rather than sweet", "塩気のある、ピリッとした（甘くない）", "I prefer a savory breakfast over a sweet one.", "B2"],
  ["ferment", "fer-MENT", "verb/noun", "To undergo a chemical change in food production", "発酵する", "Soybeans ferment to make natto and soy sauce.", "B2"],
  ["cuisine", "kwi-ZEEN", "noun", "A style or method of cooking, especially as characteristic of a particular country, region, or establishment", "料理、クイジーン", "Japanese cuisine is famous for sushi and ramen.", "B1"],
  ["ingredient", "in-GREE-dee-uhnt", "noun", "Any of the foods or substances that are combined to make a particular dish", "食材、成分", "Fresh ginger is an important ingredient in this soup.", "B1"],
  ["appetizer", "AP-i-tahy-zer", "noun", "A small dish of food or a drink taken before a meal to stimulate the appetite", "前菜", "We ordered spring rolls as an appetizer.", "B1"],
  ["dessert", "dih-ZURT", "noun", "The sweet course eaten at the end of a meal", "デザート", "We had matcha ice cream for dessert.", "A2"],
  ["beverage", "BEV-er-ij", "noun", "A drink other than water", "飲み物、飲料", "Tea is a popular beverage in Asia.", "B2"],
  ["snack", "SNAK", "noun/verb", "A small amount of food eaten between meals", "おやつ、軽食", "He grabbed a quick snack between lessons.", "A1"],
  ["seasoning", "SEE-zuh-ning", "noun", "Salt, herbs, or spices added to food to enhance the flavor", "調味料", "This soup needs some more seasoning.", "B1"],
  ["flavor", "FLEY-ver", "noun/verb", "The distinctive taste of a food or drink", "味、風味", "Vanilla is a popular flavor for cakes.", "A2"],
  ["buffet", "buh-FEY", "noun", "A meal consisting of several dishes from which guests serve themselves", "ビュッフェ、バイキング", "The hotel offered a breakfast buffet.", "B1"],
  ["menu", "MEN-yoo", "noun", "A list of dishes available in a restaurant", "メニュー", "Let's ask the waiter for the menu.", "A1"],
  ["chef", "SHEF", "noun", "A professional cook", "シェフ、料理長", "The head chef prepared the special sushi.", "A2"],
  ["nutrition", "noo-TRISH-uhs", "noun", "The process of providing or obtaining the food necessary for health and growth", "栄養", "A balanced diet provides good nutrition.", "B2"],
  ["diet", "DAHY-it", "noun/verb", "The kinds of food that a person, animal, or community habitually eats", "食生活、ダイエット", "A healthy diet is key to long life.", "A2"],
  ["allergy", "AL-er-jee", "noun", "A damaging immune response by the body to a substance", "アレルギー", "He has a peanut allergy.", "B1"],
  ["recipe", "RES-uh-pee", "noun", "Instructions", "レシピ", "My grandmother gave me this recipe.", "A2"],
  ["leftover", "LEF-toh-ver", "noun/adjective", "Something, especially food, remaining after the rest has been used", "残り物", "We ate leftover pizza for lunch.", "B1"],
  ["feast", "FEEST", "noun/verb", "A large meal, typically one in celebration of something", "ごちそう、祝宴", "The New Year feast lasted all day.", "B2"],
  ["banquet", "BANG-kwit", "noun", "An elaborate and formal evening meal for many people", "晩餐会、宴会", "They held a grand banquet at the palace.", "B2"],
  ["sweet", "SWEET", "adjective/noun", "Having the pleasant taste characteristic of sugar or honey", "甘い", "I like sweet chocolate.", "A1"],
  ["sour", "SOW-er", "adjective", "Having an acid taste like lemon or vinegar", "酸っぱい", "Lemons are sour.", "A2"],
  ["bitter", "BIT-er", "adjective", "Having a sharp, pungent taste or smell", "苦い", "Black coffee is bitter.", "A2"],
  ["salty", "SAWL-tee", "adjective", "Tasting of, containing, or preserved with salt", "塩辛い", "Potato chips are salty.", "A2"],
  ["spicy", "SPAHY-see", "adjective", "Flavored with or fragrant with spice", "辛い、スパイシーな", "I like spicy curry.", "A2"],
  ["bland", "BLAND", "adjective", "Lacking strong features or characteristics and therefore uninteresting", "薄味の、味気ない", "Hospital food can be bland.", "B2"],
  ["crispy", "KRIS-pee", "adjective", "Pleasantly thin, dry, and easily broken", "サクサクした、パリパリした", "The fried chicken was hot and crispy.", "B1"],
  ["crunchy", "KRUHN-chee", "adjective", "Making a sharp noise when bitten or crushed", "バリバリした、カリカリした", "Fresh carrots are crunchy.", "B1"],
  ["tender", "TEN-der", "adjective", "Easy to cut or chew; not tough", "柔らかい", "The beef was cooked until tender.", "B2"],
  ["tough", "TUHF", "adjective", "Difficult to cut or chew", "固い", "The meat was tough and overcooked.", "B2"],
  ["fresh", "FRESH", "adjective", "Recently made or obtained; not canned or frozen", "新鮮な", "We buy fresh fruit every morning.", "A1"],
  ["stale", "STEYL", "adjective", "No longer fresh and pleasant to eat; hard, musty, or dry", "古くなった、ぱさぱさした", "Don't eat that stale bread.", "B1"],
  ["raw", "RAW", "adjective", "Not cooked", "生の", "Sashimi is raw fish.", "B1"],
  ["cooked", "KOOKT", "adjective", "Prepared by heating", "調理された", "Cooked vegetables are easy to digest.", "A1"],
  ["baked", "BEYKT", "adjective", "Cooked by dry heat without direct exposure to a flame, typically in an oven", "オーブンで焼いた", "I love baked apples.", "A2"],
  ["fried", "FRAHYD", "adjective", "Cooked in hot fat or oil", "揚げた、炒めた", "Fried rice is a quick meal.", "A2"],
  ["steamed", "STEEMD", "adjective", "Cooked by steam", "蒸した", "Steamed buns are popular in winter.", "B1"],
  ["grilled", "GRILD", "adjective", "Cooked on a grill", "網焼きにした", "We had grilled salmon.", "A2"],
  ["roasted", "ROHST-tid", "adjective", "Cooked by roasting", "ローストした、焙煎した", "He likes roasted coffee beans.", "B1"],
  ["boiled", "BOILD", "adjective", "Cooked in boiling water", "茹でた", "Boiled eggs are easy to make.", "A2"],
  ["ripe", "RAHP", "adjective", "Developed to the point of readiness for harvesting and eating", "熟した", "The bananas are ripe.", "B1"],
  ["rotten", "ROT-n", "adjective", "Decaying or decayed and fallen into ruin", "腐った", "Throw away the rotten tomatoes.", "B1"],
  ["delicious", "dih-LISH-uhs", "adjective", "Highly pleasant to the taste", "おいしい", "That was a delicious lunch.", "A1"],
  ["exotic", "ig-ZOT-ik", "adjective", "Originating in or characteristic of a distant foreign country", "異国情緒のある、珍しい", "We tried some exotic fruits on vacation.", "B2"],
  ["traditional", "truh-DISH-uh-nuhl", "adjective/noun", "Local style", "伝統的な料理", "They serve traditional washoku.", "B1"],
  ["imported", "im-PAWR-tid", "adjective/verb", "Brought in from another country", "輸入された", "Imported cheese can be expensive.", "B1"],
  ["local", "LOH-kuhl", "adjective/noun", "Nearby", "地元の", "We bought local strawberries.", "A2"],
  ["homemade", "HOHM-MEYD", "adjective", "Made at home", "自家製の、手作りの", "I love homemade apple pie.", "A2"],
  ["processed", "PROS-esd", "adjective/verb", "Preserved food", "加工された", "Processed food has too much salt.", "B2"],
  ["healthy", "HEL-thee", "adjective", "Good for health", "健康的な", "Eating salad is healthy.", "A2"]
];

food.forEach(row => addWord(row[0], row[1], row[2], row[3], row[4], row[5], row[6], "food"));

// 7. internet (50 words)
const internet = [
  ["literally", "LIT-er-uh-lee", "adverb", "In a literal manner or sense; exactly", "文字通り、本当に", "I was literally the only student in class.", "B1"],
  ["wild", "WAHYLD", "adjective", "Uncontrolled; crazy or exciting", "ヤバい、めちゃくちゃな", "His reaction to the food was wild.", "A2"],
  ["vibe", "VAHYB", "noun/verb", "A person's emotional state or the atmosphere of a place", "雰囲気、バイブス", "This cafe has a really chill lofi vibe.", "B1"],
  ["lowkey", "LOH-kee", "adverb", "To some extent; secretly or subtly", "実は、控えめに言えば", "I lowkey want to stay home and watch anime.", "B2"],
  ["highkey", "HAHY-kee", "adverb", "Clearly, obviously, or intensely", "本当に、明らかに", "I highkey love this theme song.", "B2"],
  ["based", "BEYST", "adjective", "True to oneself; not caring what others think", "ブレない、イケてる", "That was a based opinion.", "C1"],
  ["deadass", "DED-as", "adverb", "Seriously; truthfully", "ガチで、大真面目で", "I am deadass not joking about the homework.", "C1"],
  ["slay", "SLEY", "verb", "To do something exceptionally well", "イケてる、大成功する", "You absolutely slayed that presentation.", "B2"],
  ["ratio", "REY-shee-oh", "noun/verb", "When a reply gets more likes than the original post", "（ネット用語の）比率、やり返すこと", "He got ratioed on Twitter.", "B2"],
  ["bussin", "BUHS-in", "adjective", "Extremely delicious", "めちゃくちゃうまい", "This ramen is deadass bussin.", "C1"],
  ["sheesh", "SHEESH", "interjection", "Expression of disbelief or shock", "うわー、すげえ", "Sheesh, look at that giant slice of cake.", "B2"],
  ["no cap", "noh KAP", "phrase", "No lie; seriously", "ガチで、嘘偽りなし", "He can eat five burgers, no cap.", "B2"],
  ["slang", "SLANG", "noun", "A type of language that consists of words and phrases that are regarded as very informal", "俗語、スラング", "Internet slang changes so fast.", "B2"],
  ["meme", "MEEM", "noun", "A humorous image, video, piece of text, etc., that is copied and spread rapidly by internet users", "ミーム", "That CaseOh meme was so funny.", "B1"],
  ["viral", "VAHY-ruhl", "adjective", "Spreading widely and rapidly on the internet", "バイラル、拡散された", "His reaction video went viral.", "B1"],
  ["trending", "TREND-ing", "adjective/verb", "Currently popular on social media", "トレンド入りしている", "Lofi music is trending right now.", "B1"],
  ["algorithm", "AL-guh-rith-uhm", "noun", "A process or set of rules to be followed in calculations", "アルゴリズム", "The YouTube algorithm recommended a cooking clip.", "B2"],
  ["profile", "PROH-fahyl", "noun", "An outline of something, especially a person's face, as seen from one side", "プロフィール", "Update your profile avatar.", "A2"],
  ["avatar", "AV-uh-tahr", "noun", "An icon or figure representing a particular person in a computer game, Internet forum, etc.", "アバター、アイコン", "She chose a sakura leaf for her avatar.", "B1"],
  ["subscriber", "suhb-SKRAHY-ber", "noun", "A person who subscribes to a publication, channel, or service", "登録者、チャンネル購読者", "The streamer reached one million subscribers.", "B1"],
  ["follower", "FOL-oh-er", "noun", "An adherent or devotee of a particular person, cause, or activity", "フォロワー", "He gained ten thousand followers overnight.", "A2"],
  ["influencer", "IN-floo-uhn-ser", "noun", "A person with the ability to influence potential buyers of a product or service by recommending it on social media", "インフルエンサー", "She is a popular beauty influencer.", "B1"],
  ["streamer", "STREEM-er", "noun", "A person who broadcasts material live over the internet", "配信者、ストリーマー", "CaseOh is a famous gaming streamer.", "B1"],
  ["broadcast", "BRAWD-kast", "noun/verb", "Transmit by radio or television", "放送、ライブ配信", "He starts his live broadcast at eight.", "B1"],
  ["podcast", "POD-kast", "noun/verb", "A digital audio file made available on the internet for downloading", "ポッドキャスト", "I listen to an English podcast.", "B1"],
  ["comment", "KOM-ent", "noun/verb", "A verbal or written remark expressing an opinion or reaction", "コメント", "I left a comment on the video.", "A2"],
  ["feedback", "FEED-bak", "noun", "Information about reactions to a product, a person's performance of a task, etc.", "フィードバック", "The teacher gives constructive feedback.", "B2"],
  ["notifications", "noh-tuh-fi-KEY-shuhnz", "noun", "A message that is sent to a phone or computer to inform the user about something", "通知", "Turn on notifications for homework due.", "B1"],
  ["app", "AP", "noun", "An application, especially as downloaded by a user to a mobile device", "アプリ", "We study English on a mobile app.", "A1"],
  ["website", "WEB-sahyt", "noun", "A set of related web pages located under a single domain name", "ウェブサイト", "The website has a responsive layout.", "A1"],
  ["link", "LINGK", "noun/verb", "A relationship between two things", "リンク、URL", "Click the link to open the page.", "A1"],
  ["username", "YOOS-er-neym", "noun", "An identification used by a person with access to a computer, network, or online service", "ユーザー名", "Choose a unique username.", "A2"],
  ["password", "PAS-wurd", "noun", "A secret word or phrase that must be used to gain admission to something", "パスワード", "Keep your password safe.", "A1"],
  ["security", "si-KYOOR-i-tee", "noun", "The state of being free from danger or threat", "セキュリティ", "Database security is crucial.", "B1"],
  ["privacy", "PRAHY-vuh-see", "noun", "The state or condition of being free from public attention", "プライバシー", "We protect user privacy.", "B1"],
  ["database", "DEY-tuh-beys", "noun", "A structured set of data held in a computer, especially one that is accessible in various ways", "データベース", "The word library is saved in a database.", "B2"],
  ["chat", "CHAT", "noun/verb", "Talk in a friendly and informal way", "チャット", "Streamer often talks to chat.", "A1"],
  ["online", "ON-lahyn", "adjective/adverb", "Controlled by or connected to another computer", "オンラインの", "I did the placement test online.", "A1"],
  ["offline", "AWF-lahyn", "adjective/adverb", "Not connected to a computer", "オフラインの", "The speech API works offline.", "B1"],
  ["wifi", "WAHY-fahy", "noun", "A facility allowing computers, smartphones, or other devices to connect to the internet", "ワイファイ", "The hotel had free wifi.", "A1"],
  ["signal", "SIG-nl", "noun/verb", "An electrical impulse or radio wave transmitted or received", "電波、シグナル", "The mobile signal was weak in valley.", "B1"],
  ["browser", "BROW-zer", "noun", "A program with a graphical user interface for displaying HTML files", "ブラウザ", "Open the link in a mobile browser.", "A2"],
  ["download", "DOWN-lohd", "verb/noun", "Copy data from one computer system to another, typically over the internet", "ダウンロードする", "You can download the notes as text.", "A2"],
  ["upload", "UHP-lohd", "verb/noun", "Transfer data from one computer to another, typically to a larger central server", "アップロードする", "I uploaded my voice file for check.", "B1"],
  ["interactive", "in-ter-AK-tiv", "adjective", "Allowing two-way flow of information between a computer and a user", "インタラクティブな", "The quiz is interactive.", "B1"],
  ["digital", "DIJ-i-tl", "adjective", "Expressed as series of the digits 0 and 1", "デジタルな", "A digital dictionary is convenient.", "B1"],
  ["virtual", "VUR-choo-uhl", "adjective", "Almost or nearly as described, but not completely or according to strict definition", "仮想の、バーチャルな", "We met in a virtual room.", "B1"],
  ["responsive", "ri-SPON-siv", "adjective", "Responding readily and warmly", "レスポンシブな、反応が良い", "The layout is responsive on mobile.", "B2"],
  ["global", "GLOH-buhl", "adjective", "Relating to the whole world; worldwide", "グローバルな、全体の", "The notes widget is mounted globally.", "B1"],
  ["local", "LOH-kuhl", "adjective/noun", "Nearby", "ローカルな、ローカルの", "The files are saved in local storage.", "A2"]
];

internet.forEach(row => addWord(row[0], row[1], row[2], row[3], row[4], row[5], row[6], "internet"));

// 8. travel (40 words)
const travel = [
  ["itinerary", "ahy-TIN-uh-rer-ee", "noun", "A planned route or journey", "旅程、旅行計画", "She wrote a detailed itinerary for Tokyo.", "C1"],
  ["luggage", "LUHG-ij", "noun", "Suitcases and bags containing a traveler's belongings", "手荷物、ラゲッジ", "We left our luggage at the hotel lobby.", "A2"],
  ["boarding", "BAWR-ding", "noun/adjective", "The action of getting on a ship, train, or plane", "搭乗、搭乗の", "Boarding starts thirty minutes before departure.", "A2"],
  ["departure", "dih-PAHR-cher", "noun", "The action of leaving, especially to start a journey", "出発", "The flight departure was delayed.", "B1"],
  ["destination", "des-tuh-NEY-shuhn", "noun", "The place to which someone or something is going or being sent", "目的地、行先", "Nara is a popular tourist destination.", "B1"],
  ["arrival", "uh-RAHY-vuhl", "noun", "The action of arriving", "到着", "Her arrival time was set for morning.", "A2"],
  ["sightseeing", "SAHYT-see-ing", "noun", "The activity of visiting places of interest in a particular location", "観光", "We did some sightseeing in Kyoto.", "A2"],
  ["accommodation", "uh-kom-uh-DEY-shuhn", "noun", "A room, group of rooms, or building in which someone may live or stay", "宿泊施設", "Hotel accommodation can be expensive in spring.", "B2"],
  ["reservation", "rez-er-VEY-shuhn", "noun", "An arrangement to have something kept for a particular person", "予約", "I made a dinner reservation.", "B1"],
  ["souvenir", "soo-vuh-NEER", "noun", "A thing that is kept as a reminder of a person, place, or event", "お土産", "I bought a cherry blossom fan as a souvenir.", "A2"],
  ["passport", "PAS-pawrt", "noun", "An official document issued by a government, certifying the holder's identity and citizenship", "パスポート", "Don't forget your passport.", "A1"],
  ["visa", "VEE-zuh", "noun", "An endorsement on a passport indicating that the holder is allowed to enter, leave, or stay for a specified period", "ビザ、査証", "I applied for a student visa.", "B1"],
  ["transit", "TRAN-sit", "noun/verb", "The carrying of people, goods, or materials from one place to another", "乗り換え、トランジット", "We were in transit at the airport.", "B2"],
  ["customs", "KUHS-tuhmz", "noun", "The place at a port, airport, or frontier where officials check incoming goods, travelers, or luggage", "税関", "Going through customs took an hour.", "B2"],
  ["delayed", "dih-LEYD", "adjective/verb", "Late", "遅れた", "My flight was delayed.", "A2"],
  ["cancelled", "KAN-suhld", "adjective/verb", "Called off", "欠航した、キャンセルされた", "The train was cancelled due to snow.", "A2"],
  ["baggage", "BAG-ij", "noun", "Luggage", "手荷物", "We collected our baggage.", "A2"],
  ["terminal", "TUR-muh-nl", "noun/adjective", "A departure and arrival building", "ターミナル", "Go to terminal two for domestic flights.", "B1"],
  ["ticket", "TIK-it", "noun", "A piece of paper or card that gives the holder a certain right", "切符、チケット", "I bought a train ticket.", "A1"],
  ["journey", "JUR-nee", "noun/verb", "An act of traveling from one place to another", "旅、道のり", "English study is a long journey.", "A2"],
  ["voyage", "VOI-ij", "noun/verb", "A long journey involving travel by sea or in space", "船旅、長い旅", "The sea voyage was calm.", "B2"],
  ["flight", "FLAHT", "noun", "An act or instance of passing through the air by use of wings", "飛行機、フライト", "The flight takes twelve hours.", "A1"],
  ["cruise", "KROOZ", "noun/verb", "A voyage on a ship or boat taken for pleasure", "クルーズ", "They went on a river cruise.", "B1"],
  ["expedition", "ek-spih-DISH-uhn", "noun", "A journey or voyage undertaken by a group of people with a particular purpose", "遠征、探検旅行", "The scientific expedition went to the polar region.", "B2"],
  ["tourist", "TOOR-ist", "noun/adjective", "A person who is traveling or visiting a place for pleasure", "観光客", "The temple was full of tourists.", "A2"],
  ["traveler", "TRAV-uh-ler", "noun", "A person who is traveling or who often travels", "旅行者", "He is an experienced traveler.", "A2"],
  ["guidebook", "GAHD-book", "noun", "A book of information about a place, designed for the use of visitors or tourists", "ガイドブック", "I bought a guidebook for my trip.", "A2"],
  ["monument", "MON-yuh-muhnt", "noun", "A statue, building, or other structure erected to commemorate a famous person or event", "記念碑、モニュメント", "We visited the historic monument.", "B2"],
  ["landmark", "LAND-mahrk", "noun", "An object or feature of a landscape or town that is easily seen and recognized from a distance", "目印、ランドマーク", "Tokyo Tower is an iconic landmark.", "B1"],
  ["scenery", "SEEN-uh-ree", "noun", "Landscape", "風景", "The train route offers scenic view.", "A2"],
  ["scenic", "SEEN-ik", "adjective/noun", "Scenic views", "景観が良い", "We took a scenic tour.", "B1"],
  ["historic", "his-TAWR-ik", "adjective", "Famous or important in history", "歴史的な", "We visited a historic temple.", "B1"],
  ["exotic", "ig-ZOT-ik", "adjective/noun", "Different place", "異国の", "I like to visit exotic locations.", "B2"],
  ["cozy", "KOH-zee", "adjective/noun", "Warm hotel style", "居心地が良い", "Our guesthouse was cozy.", "A2"],
  ["luxurious", "luhg-ZHOOR-ee-uhs", "adjective", "Extremely comfortable, elegant, or enjoyable, especially in a way that involves great expense", "豪華な、贅沢な", "The hotel lobby was luxurious.", "B2"],
  ["affordable", "uh-FAWR-duh-buhl", "adjective", "Inexpensive; reasonably priced", "手頃な価格の", "The hostel was clean and affordable.", "B1"],
  ["cheap", "CHEEP", "adjective/adverb", "Low in price", "安い", "Street food is cheap and tasty.", "A1"],
  ["expensive", "ik-SPEN-siv", "adjective", "Costing a lot of money", "高価な", "Flights can be expensive during holidays.", "A1"],
  ["comfortable", "KUHMF-ter-buhl", "adjective", "Providing physical ease and relaxation", "快適な", "The train seats were comfortable.", "A2"],
  ["adventurous", "ad-VEN-cher-uhs", "adjective", "Willing to take risks or to try out new methods, ideas, or experiences", "冒険好きな", "She is an adventurous traveler.", "B2"]
];

travel.forEach(row => addWord(row[0], row[1], row[2], row[3], row[4], row[5], row[6], "travel"));

// 9. academic (30 words)
const academic = [
  ["thesis", "THEE-sis", "noun", "A statement or theory that is put forward as a premise to be maintained or proved", "論文、テーゼ", "She is writing her graduation thesis.", "C1"],
  ["hypothesis", "hahy-POTH-uh-sis", "noun", "A proposed explanation made on the basis of limited evidence", "仮説", "We conducted an experiment to test the hypothesis.", "C1"],
  ["curriculum", "kuh-RIK-yuh-luhm", "noun", "The subjects comprising a course of study in a school or college", "カリキュラム", "The 90-day curriculum is structured logically.", "B2"],
  ["syllabus", "SIL-uh-buhs", "noun", "An outline of the subjects in a course of study", "シラバス、講義計画", "The teacher handed out the syllabus.", "B2"],
  ["pedagogy", "PED-uh-goh-jee", "noun", "The method and practice of teaching, especially as an academic subject or theoretical concept", "教育学、指導法", "The app uses an active pedagogy model.", "C1"],
  ["evaluation", "ih-val-yoo-EY-shuhn", "noun", "The making of a judgment about the amount, number, or value of something", "評価", "Your placement level evaluation is automatic.", "B2"],
  ["criteria", "krahy-TEER-ee-uh", "noun", "A principle or standard by which something may be judged or decided", "基準、評価尺度", "Word count is one of the criteria for diary review.", "B2"],
  ["assessment", "uh-SES-muhnt", "noun", "The evaluation or estimation of the nature, quality, or ability of someone or something", "アセスメント、査定", "A weekly assessment tracks progress.", "B2"],
  ["cognition", "kog-NISH-uhn", "noun", "The mental action or process of acquiring knowledge and understanding through thought, experience, and the senses", "認知、認識", "Spaced repetition optimizes memory cognition.", "C1"],
  ["comprehension", "kom-pri-HEN-shuhn", "noun", "The action or capability of understanding something", "理解、読解", "The video comprehension score was eighty percent.", "B2"],
  ["fluency", "FLOO-uhn-see", "noun", "The ability to speak or write a foreign language easily and accurately", "流暢さ", "Constant speaking practice improves fluency.", "B2"],
  ["accuracy", "AK-yer-uh-see", "noun", "The quality or state of being correct or precise", "正確さ", "The teacher checks our diary for grammatical accuracy.", "B2"],
  ["feedback", "FEED-bak", "noun/adjective", "Correction notes", "フィードバック", "I appreciate academic feedback.", "B2"],
  ["memorization", "mem-er-uh-ZEY-shuhn", "noun", "The process of committing something to memory", "暗記", "Rote memorization can be monotonous.", "B2"],
  ["discipline", "DIS-uh-plin", "noun/verb", "The practice of training people to obey rules", "規律、自制", "Studying daily takes discipline.", "B1"],
  ["motivation", "moh-tuh-VEY-shuhn", "noun", "The reason or reasons one has for acting or behaving in a particular way", "モチベーション、動機", "Streak scores keep motivation high.", "B1"],
  ["achievement", "uh-CHEEV-muhnt", "noun", "A thing done successfully, typically by effort, courage, or skill", "実績、達成", "Mastering 300 words is a major achievement.", "B1"],
  ["objective", "uhb-JEK-tiv", "noun/adjective", "A goal", "目的、客観的な", "The study objective is clear.", "B1"],
  ["subjective", "suhb-JEK-tiv", "adjective", "Based on or influenced by personal feelings, tastes, or opinions", "主観的な", "Comprehension rating is subjective.", "B2"],
  ["cognitive", "KOG-ni-tiv", "adjective", "Relating to cognition", "認知の", "Learning English involves cognitive effort.", "B2"],
  ["pedagogical", "ped-uh-GOJ-i-kuhl", "adjective", "Relating to teaching", "教育上の", "The lesson cards use pedagogical patterns.", "C1"],
  ["academic", "ak-uh-DEM-ik", "adjective/noun", "Relating to education and scholarship", "学術的な", "This is an academic study tool.", "B1"],
  ["scholarly", "SKOL-er-lee", "adjective", "Involving or relating to serious academic study", "学術的な、博学な", "The guidebook referenced scholarly articles.", "C1"],
  ["theoretical", "thee-uh-RET-i-kuhl", "adjective", "Concerned with or involving the theory of a subject or area of study rather than its practical application", "理論的な", "Grammar rules provide a theoretical framework.", "B2"],
  ["empirical", "em-PIR-i-kuhl", "adjective", "Based on, concerned with, or verifiable by observation or experience rather than theory or pure logic", "実証的な", "Our study tips are based on empirical research.", "C1"],
  ["logical", "LOJ-i-kuhl", "adjective", "Of or according to the rules of logic", "論理的な", "The grammar pattern card is very logical.", "B1"],
  ["analytical", "an-uh-LIT-i-kuhl", "adjective", "Relating to or using analysis or logical reasoning", "分析的な", "The progress page offers analytical charts.", "B2"],
  ["systematic", "sis-tuh-MAT-ik", "adjective", "Done or acting according to a fixed plan or system; methodical", "体系的な", "We follow a systematic curriculum.", "B2"],
  ["structured", "STRUHK-cherd", "adjective/verb", "Organized", "構造化された", "Lessons have a highly structured design.", "B1"],
  ["comprehensive", "kom-pri-HEN-siv", "adjective/noun", "Complete; including all or nearly all elements or aspects of something", "包括的な", "The library has a comprehensive list.", "B2"]
];

academic.forEach(row => addWord(row[0], row[1], row[2], row[3], row[4], row[5], row[6], "academic"));

// Output file path
const outputPath = path.join(__dirname, '..', 'data', 'word_library.json');

// Write file
fs.writeFileSync(outputPath, JSON.stringify(library, null, 2), 'utf8');
console.log(`Successfully generated 500 words to ${outputPath}`);
